/**
 * EE ZONE — Local Code Generation Engine
 * Generates production-ready embedded code for PLC, Arduino, and ESP32
 * without requiring any external API keys.
 */

// ─── Template Definitions ────────────────────────────────────────────

interface CodeTemplate {
  keywords: string[];
  title: string;
  description: string;
  code: string;
}

// ─── ARDUINO TEMPLATES ──────────────────────────────────────────────

const arduinoTemplates: CodeTemplate[] = [
  {
    keywords: ['blink', 'led', 'flash', 'light'],
    title: 'LED Blink',
    description: 'Blink an LED with configurable timing',
    code: `/*
 * LED Blink Controller
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Blinks an LED on the specified pin with configurable
 * on/off timing. Includes serial monitoring.
 */

// ── Pin Definitions ──────────────────────────
const int LED_PIN = 13;          // Built-in LED on most boards

// ── Timing Configuration ─────────────────────
const unsigned long ON_TIME  = 1000;  // LED on duration (ms)
const unsigned long OFF_TIME = 1000;  // LED off duration (ms)

// ── State Variables ──────────────────────────
unsigned long previousMillis = 0;
bool ledState = false;
unsigned long blinkCount = 0;

void setup() {
  Serial.begin(9600);
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);

  Serial.println(F("=== EE ZONE LED Blink Controller ==="));
  Serial.print(F("LED Pin: "));
  Serial.println(LED_PIN);
  Serial.print(F("On Time: "));
  Serial.print(ON_TIME);
  Serial.println(F(" ms"));
  Serial.print(F("Off Time: "));
  Serial.print(OFF_TIME);
  Serial.println(F(" ms"));
  Serial.println(F("System ready. Blinking started."));
}

void loop() {
  unsigned long currentMillis = millis();
  unsigned long interval = ledState ? ON_TIME : OFF_TIME;

  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    ledState = !ledState;
    digitalWrite(LED_PIN, ledState ? HIGH : LOW);

    if (ledState) {
      blinkCount++;
      Serial.print(F("Blink #"));
      Serial.print(blinkCount);
      Serial.println(F(" - LED ON"));
    } else {
      Serial.println(F("         LED OFF"));
    }
  }
}`
  },
  {
    keywords: ['temperature', 'temp', 'sensor', 'dht', 'thermometer', 'humidity', 'dht11', 'dht22', 'lm35'],
    title: 'Temperature & Humidity Monitor',
    description: 'DHT11/DHT22 temperature and humidity sensor reading',
    code: `/*
 * Temperature & Humidity Monitor
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Reads temperature and humidity from a DHT sensor.
 * Includes averaging filter, alarm threshold, and serial output.
 */

#include <DHT.h>

// ── Pin Definitions ──────────────────────────
#define DHT_PIN       2       // DHT data pin
#define DHT_TYPE      DHT11   // DHT11 or DHT22
#define ALARM_LED_PIN 13      // Alarm indicator LED
#define BUZZER_PIN    8       // Alarm buzzer

// ── Configuration ────────────────────────────
const float TEMP_ALARM_HIGH = 50.0;   // °C - High temperature alarm
const float TEMP_ALARM_LOW  = -10.0;  // °C - Low temperature alarm
const float HUMIDITY_ALARM  = 85.0;   // % - High humidity alarm
const int   READ_INTERVAL   = 2000;   // ms between readings
const int   FILTER_SAMPLES  = 5;      // Moving average samples

// ── Objects & Variables ──────────────────────
DHT dht(DHT_PIN, DHT_TYPE);

float tempReadings[5];
float humReadings[5];
int   readIndex = 0;
bool  bufferFull = false;
unsigned long lastReadTime = 0;
unsigned long readingCount = 0;

void setup() {
  Serial.begin(9600);
  dht.begin();

  pinMode(ALARM_LED_PIN, OUTPUT);
  pinMode(BUZZER_PIN, OUTPUT);
  digitalWrite(ALARM_LED_PIN, LOW);
  digitalWrite(BUZZER_PIN, LOW);

  // Initialize filter arrays
  for (int i = 0; i < FILTER_SAMPLES; i++) {
    tempReadings[i] = 0;
    humReadings[i] = 0;
  }

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║  EE ZONE Temperature Monitor v1.0   ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.print(F("Sensor: DHT"));
  Serial.println(DHT_TYPE == DHT11 ? "11" : "22");
  Serial.print(F("Alarm Thresholds - High: "));
  Serial.print(TEMP_ALARM_HIGH);
  Serial.print(F("°C, Low: "));
  Serial.print(TEMP_ALARM_LOW);
  Serial.println(F("°C"));
  Serial.println(F("────────────────────────────────────────"));
}

void loop() {
  unsigned long now = millis();
  if (now - lastReadTime < READ_INTERVAL) return;
  lastReadTime = now;

  float temp = dht.readTemperature();
  float hum  = dht.readHumidity();

  // Validate readings
  if (isnan(temp) || isnan(hum)) {
    Serial.println(F("[ERROR] Failed to read from DHT sensor!"));
    return;
  }

  // Store in filter buffer
  tempReadings[readIndex] = temp;
  humReadings[readIndex]  = hum;
  readIndex = (readIndex + 1) % FILTER_SAMPLES;
  if (readIndex == 0) bufferFull = true;

  // Calculate averages
  int count = bufferFull ? FILTER_SAMPLES : readIndex;
  float avgTemp = 0, avgHum = 0;
  for (int i = 0; i < count; i++) {
    avgTemp += tempReadings[i];
    avgHum  += humReadings[i];
  }
  avgTemp /= count;
  avgHum  /= count;

  readingCount++;

  // Check alarms
  bool alarm = (avgTemp > TEMP_ALARM_HIGH) ||
               (avgTemp < TEMP_ALARM_LOW) ||
               (avgHum > HUMIDITY_ALARM);

  digitalWrite(ALARM_LED_PIN, alarm ? HIGH : LOW);
  if (alarm) {
    tone(BUZZER_PIN, 2000, 200);
  }

  // Serial output
  Serial.print(F("#"));
  Serial.print(readingCount);
  Serial.print(F("  Temp: "));
  Serial.print(avgTemp, 1);
  Serial.print(F("°C  Hum: "));
  Serial.print(avgHum, 1);
  Serial.print(F("%"));
  if (alarm) Serial.print(F("  ⚠ ALARM!"));
  Serial.println();
}`
  },
  {
    keywords: ['motor', 'dc motor', 'speed', 'pwm', 'h-bridge', 'l298', 'l293', 'direction'],
    title: 'DC Motor Controller',
    description: 'PWM motor speed control with direction and safety',
    code: `/*
 * DC Motor Speed & Direction Controller
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Controls a DC motor via L298N/L293D H-bridge driver.
 * Features: PWM speed control, direction, soft start/stop,
 * serial command interface, and overcurrent protection.
 */

// ── Pin Definitions (L298N H-Bridge) ─────────
const int ENA_PIN = 9;    // PWM speed control (Enable A)
const int IN1_PIN = 7;    // Direction control 1
const int IN2_PIN = 6;    // Direction control 2
const int CURRENT_SENSE_PIN = A0; // Current sense (optional)

// ── Configuration ────────────────────────────
const int   PWM_MIN         = 0;
const int   PWM_MAX         = 255;
const float OVERCURRENT_MA  = 2000.0;   // 2A overcurrent limit
const int   RAMP_STEP       = 5;        // Speed ramp increment
const int   RAMP_DELAY      = 20;       // ms between ramp steps

// ── State Variables ──────────────────────────
int  currentSpeed   = 0;
int  targetSpeed    = 0;
bool motorDirection = true;  // true=CW, false=CCW
bool motorEnabled   = false;
bool overCurrentTrip = false;

void setup() {
  Serial.begin(9600);

  pinMode(ENA_PIN, OUTPUT);
  pinMode(IN1_PIN, OUTPUT);
  pinMode(IN2_PIN, OUTPUT);
  pinMode(CURRENT_SENSE_PIN, INPUT);

  stopMotor();

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║   EE ZONE DC Motor Controller v1.0  ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("Commands:"));
  Serial.println(F("  F <speed>  - Forward (0-255)"));
  Serial.println(F("  R <speed>  - Reverse (0-255)"));
  Serial.println(F("  S          - Stop"));
  Serial.println(F("  B          - Brake (hard stop)"));
  Serial.println(F("  ?          - Show status"));
  Serial.println(F("────────────────────────────────────────"));
}

void loop() {
  // Check overcurrent
  checkCurrent();

  // Ramp speed smoothly
  rampSpeed();

  // Handle serial commands
  if (Serial.available()) {
    handleCommand();
  }
}

void handleCommand() {
  char cmd = Serial.read();
  cmd = toupper(cmd);

  switch (cmd) {
    case 'F': {
      int spd = Serial.parseInt();
      spd = constrain(spd, 0, PWM_MAX);
      motorDirection = true;
      targetSpeed = spd;
      motorEnabled = true;
      overCurrentTrip = false;
      setDirection(true);
      Serial.print(F(">> Forward, speed: "));
      Serial.println(spd);
      break;
    }
    case 'R': {
      int spd = Serial.parseInt();
      spd = constrain(spd, 0, PWM_MAX);
      motorDirection = false;
      targetSpeed = spd;
      motorEnabled = true;
      overCurrentTrip = false;
      setDirection(false);
      Serial.print(F(">> Reverse, speed: "));
      Serial.println(spd);
      break;
    }
    case 'S':
      targetSpeed = 0;
      Serial.println(F(">> Stopping (soft)"));
      break;
    case 'B':
      brakeMotor();
      Serial.println(F(">> BRAKE applied"));
      break;
    case '?':
      printStatus();
      break;
  }
}

void setDirection(bool forward) {
  if (forward) {
    digitalWrite(IN1_PIN, HIGH);
    digitalWrite(IN2_PIN, LOW);
  } else {
    digitalWrite(IN1_PIN, LOW);
    digitalWrite(IN2_PIN, HIGH);
  }
}

void rampSpeed() {
  static unsigned long lastRamp = 0;
  if (millis() - lastRamp < RAMP_DELAY) return;
  lastRamp = millis();

  if (overCurrentTrip) {
    currentSpeed = 0;
    analogWrite(ENA_PIN, 0);
    return;
  }

  if (currentSpeed < targetSpeed) {
    currentSpeed = min(currentSpeed + RAMP_STEP, targetSpeed);
  } else if (currentSpeed > targetSpeed) {
    currentSpeed = max(currentSpeed - RAMP_STEP, targetSpeed);
  }

  analogWrite(ENA_PIN, currentSpeed);

  if (currentSpeed == 0 && targetSpeed == 0) {
    motorEnabled = false;
  }
}

void stopMotor() {
  targetSpeed = 0;
  currentSpeed = 0;
  analogWrite(ENA_PIN, 0);
  digitalWrite(IN1_PIN, LOW);
  digitalWrite(IN2_PIN, LOW);
  motorEnabled = false;
}

void brakeMotor() {
  targetSpeed = 0;
  currentSpeed = 0;
  analogWrite(ENA_PIN, 255);
  digitalWrite(IN1_PIN, HIGH);
  digitalWrite(IN2_PIN, HIGH);
  delay(100);
  stopMotor();
}

void checkCurrent() {
  int raw = analogRead(CURRENT_SENSE_PIN);
  float currentMA = (raw / 1023.0) * 5000.0; // Assuming 1V/A sensor

  if (currentMA > OVERCURRENT_MA && !overCurrentTrip) {
    overCurrentTrip = true;
    stopMotor();
    Serial.println(F("⚠ OVERCURRENT DETECTED! Motor stopped."));
    Serial.print(F("  Measured: "));
    Serial.print(currentMA, 0);
    Serial.println(F(" mA"));
  }
}

void printStatus() {
  Serial.println(F("── Motor Status ──"));
  Serial.print(F("  Enabled:   ")); Serial.println(motorEnabled ? "YES" : "NO");
  Serial.print(F("  Direction: ")); Serial.println(motorDirection ? "FORWARD" : "REVERSE");
  Serial.print(F("  Speed:     ")); Serial.print(currentSpeed); Serial.print("/"); Serial.println(PWM_MAX);
  Serial.print(F("  Target:    ")); Serial.println(targetSpeed);
  Serial.print(F("  OC Trip:   ")); Serial.println(overCurrentTrip ? "YES" : "NO");
  int raw = analogRead(CURRENT_SENSE_PIN);
  float currentMA = (raw / 1023.0) * 5000.0;
  Serial.print(F("  Current:   ")); Serial.print(currentMA, 0); Serial.println(F(" mA"));
}`
  },
  {
    keywords: ['servo', 'angle', 'sweep', 'position', 'sg90'],
    title: 'Servo Motor Controller',
    description: 'Servo motor position control with serial commands',
    code: `/*
 * Servo Motor Position Controller
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Controls a servo motor angle via serial commands
 * or potentiometer input, with smooth movement.
 */

#include <Servo.h>

// ── Pin Definitions ──────────────────────────
const int SERVO_PIN = 9;
const int POT_PIN   = A0;     // Potentiometer for manual control
const int MODE_PIN  = 2;      // Switch: HIGH=manual, LOW=serial

// ── Configuration ────────────────────────────
const int ANGLE_MIN   = 0;
const int ANGLE_MAX   = 180;
const int SWEEP_DELAY = 15;   // ms per degree for sweep mode

// ── Objects & State ──────────────────────────
Servo myServo;
int currentAngle = 90;
int targetAngle  = 90;
bool sweepMode   = false;
int sweepDir     = 1;

void setup() {
  Serial.begin(9600);
  myServo.attach(SERVO_PIN);
  pinMode(MODE_PIN, INPUT_PULLUP);
  myServo.write(currentAngle);

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║   EE ZONE Servo Controller v1.0     ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("Commands: angle (0-180), 'sweep', 'center'"));
}

void loop() {
  bool manualMode = (digitalRead(MODE_PIN) == HIGH);

  if (manualMode) {
    int potVal = analogRead(POT_PIN);
    targetAngle = map(potVal, 0, 1023, ANGLE_MIN, ANGLE_MAX);
  } else if (Serial.available()) {
    String input = Serial.readStringUntil('\\n');
    input.trim();

    if (input.equalsIgnoreCase("sweep")) {
      sweepMode = !sweepMode;
      Serial.print(F("Sweep mode: "));
      Serial.println(sweepMode ? "ON" : "OFF");
    } else if (input.equalsIgnoreCase("center")) {
      sweepMode = false;
      targetAngle = 90;
      Serial.println(F("Centering to 90°"));
    } else {
      int angle = input.toInt();
      if (angle >= ANGLE_MIN && angle <= ANGLE_MAX) {
        sweepMode = false;
        targetAngle = angle;
        Serial.print(F("Moving to: "));
        Serial.print(angle);
        Serial.println(F("°"));
      }
    }
  }

  if (sweepMode) {
    targetAngle += sweepDir;
    if (targetAngle >= ANGLE_MAX || targetAngle <= ANGLE_MIN) {
      sweepDir = -sweepDir;
    }
    delay(SWEEP_DELAY);
  }

  // Smooth movement
  if (currentAngle != targetAngle) {
    if (currentAngle < targetAngle) currentAngle++;
    else currentAngle--;
    myServo.write(currentAngle);
    delay(10);
  }
}`
  },
  {
    keywords: ['lcd', 'display', 'screen', '16x2', 'i2c', 'text', 'message', 'print'],
    title: 'LCD Display Controller',
    description: 'I2C LCD display with scrolling text and sensor data',
    code: `/*
 * I2C LCD Display Controller
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Drives a 16x2 or 20x4 I2C LCD display.
 * Shows sensor data, scrolling messages, and custom characters.
 */

#include <Wire.h>
#include <LiquidCrystal_I2C.h>

// ── LCD Configuration ────────────────────────
LiquidCrystal_I2C lcd(0x27, 16, 2); // Address 0x27, 16 cols, 2 rows

// ── Custom Characters ────────────────────────
byte thermIcon[8] = {
  0b00100, 0b01010, 0b01010, 0b01010,
  0b01110, 0b11111, 0b11111, 0b01110
};

byte dropIcon[8] = {
  0b00100, 0b00100, 0b01010, 0b01010,
  0b10001, 0b10001, 0b01110, 0b00000
};

byte boltIcon[8] = {
  0b00010, 0b00110, 0b01100, 0b11111,
  0b00110, 0b01100, 0b01000, 0b00000
};

// ── Variables ────────────────────────────────
unsigned long lastUpdate = 0;
int displayPage = 0;
const int PAGES = 3;

void setup() {
  Serial.begin(9600);

  lcd.init();
  lcd.backlight();
  lcd.createChar(0, thermIcon);
  lcd.createChar(1, dropIcon);
  lcd.createChar(2, boltIcon);

  // Splash screen
  lcd.setCursor(2, 0);
  lcd.print("EE ZONE v1.0");
  lcd.setCursor(1, 1);
  lcd.print("Starting up...");
  delay(2000);
  lcd.clear();

  Serial.println(F("LCD Display Controller Ready"));
}

void loop() {
  unsigned long now = millis();
  if (now - lastUpdate >= 3000) {
    lastUpdate = now;
    displayPage = (displayPage + 1) % PAGES;
    updateDisplay();
  }

  // Handle serial input for custom messages
  if (Serial.available()) {
    String msg = Serial.readStringUntil('\\n');
    msg.trim();
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(msg.substring(0, 16));
    if (msg.length() > 16) {
      lcd.setCursor(0, 1);
      lcd.print(msg.substring(16, 32));
    }
    lastUpdate = millis() + 5000; // Pause auto-cycle
  }
}

void updateDisplay() {
  lcd.clear();

  switch (displayPage) {
    case 0: // Temperature & Humidity
      lcd.setCursor(0, 0);
      lcd.write(byte(0)); // Therm icon
      lcd.print(" Temp: 25.3");
      lcd.write(0xDF); // Degree symbol
      lcd.print("C");
      lcd.setCursor(0, 1);
      lcd.write(byte(1)); // Drop icon
      lcd.print(" Hum:  62.1%");
      break;

    case 1: // Voltage & Current
      lcd.setCursor(0, 0);
      lcd.write(byte(2)); // Bolt icon
      lcd.print(" V: 12.45V");
      lcd.setCursor(0, 1);
      lcd.print("  I:  1.23A");
      break;

    case 2: // System info
      lcd.setCursor(0, 0);
      lcd.print("Uptime:");
      lcd.setCursor(0, 1);
      unsigned long secs = millis() / 1000;
      int hrs = secs / 3600;
      int mins = (secs % 3600) / 60;
      int s = secs % 60;
      char buf[17];
      snprintf(buf, 17, " %02d:%02d:%02d", hrs, mins, s);
      lcd.print(buf);
      break;
  }
}`
  },
  {
    keywords: ['ultrasonic', 'distance', 'range', 'hcsr04', 'hc-sr04', 'sonar', 'proximity', 'obstacle'],
    title: 'Ultrasonic Distance Sensor',
    description: 'HC-SR04 ultrasonic distance measurement with filtering',
    code: `/*
 * Ultrasonic Distance Measurement System
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Uses HC-SR04 ultrasonic sensor for accurate distance
 * measurement with median filtering and alarm output.
 */

// ── Pin Definitions ──────────────────────────
const int TRIG_PIN  = 9;
const int ECHO_PIN  = 10;
const int LED_PIN   = 13;   // Proximity indicator
const int BUZZER_PIN = 8;   // Distance alarm

// ── Configuration ────────────────────────────
const float ALARM_DISTANCE_CM  = 20.0;  // Alarm threshold
const int   MEASUREMENT_COUNT  = 5;     // Median filter samples
const int   MEASURE_INTERVAL   = 100;   // ms between measurements
const float SPEED_OF_SOUND     = 0.0343; // cm/µs at ~20°C

// ── Variables ────────────────────────────────
float distances[5];
float filteredDistance = 0;
unsigned long lastMeasure = 0;
int measureIndex = 0;

void setup() {
  Serial.begin(9600);

  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
  pinMode(LED_PIN, OUTPUT);
  pinMode(BUZZER_PIN, OUTPUT);

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║  EE ZONE Ultrasonic Sensor v1.0     ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.print(F("Alarm distance: "));
  Serial.print(ALARM_DISTANCE_CM);
  Serial.println(F(" cm"));
}

void loop() {
  if (millis() - lastMeasure < MEASURE_INTERVAL) return;
  lastMeasure = millis();

  float dist = measureDistance();
  if (dist < 0) {
    Serial.println(F("[WARN] Out of range"));
    return;
  }

  // Store for median filter
  distances[measureIndex] = dist;
  measureIndex = (measureIndex + 1) % MEASUREMENT_COUNT;

  // Apply median filter
  filteredDistance = medianFilter(distances, MEASUREMENT_COUNT);

  // Alarm check
  bool alarm = filteredDistance < ALARM_DISTANCE_CM;
  digitalWrite(LED_PIN, alarm ? HIGH : LOW);
  if (alarm) {
    int freq = map(constrain((int)filteredDistance, 2, (int)ALARM_DISTANCE_CM),
                   2, (int)ALARM_DISTANCE_CM, 3000, 500);
    tone(BUZZER_PIN, freq, 50);
  } else {
    noTone(BUZZER_PIN);
  }

  // Output
  Serial.print(F("Distance: "));
  Serial.print(filteredDistance, 1);
  Serial.print(F(" cm"));
  if (alarm) Serial.print(F("  ⚠ PROXIMITY!"));
  Serial.println();
}

float measureDistance() {
  // Send trigger pulse
  digitalWrite(TRIG_PIN, LOW);
  delayMicroseconds(2);
  digitalWrite(TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);

  // Measure echo pulse
  long duration = pulseIn(ECHO_PIN, HIGH, 30000); // 30ms timeout
  if (duration == 0) return -1;

  float distance = (duration * SPEED_OF_SOUND) / 2.0;
  if (distance > 400 || distance < 2) return -1;

  return distance;
}

float medianFilter(float arr[], int size) {
  float sorted[5];
  memcpy(sorted, arr, size * sizeof(float));

  // Simple insertion sort
  for (int i = 1; i < size; i++) {
    float key = sorted[i];
    int j = i - 1;
    while (j >= 0 && sorted[j] > key) {
      sorted[j + 1] = sorted[j];
      j--;
    }
    sorted[j + 1] = key;
  }

  return sorted[size / 2];
}`
  },
  {
    keywords: ['relay', 'switch', 'on off', 'control', 'appliance', 'ac', 'mains', 'home automation'],
    title: 'Relay Control System',
    description: 'Multi-channel relay controller with safety interlocks',
    code: `/*
 * Multi-Channel Relay Control System
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Controls up to 4 relay channels with safety interlocks,
 * serial command interface, and timer-based scheduling.
 */

// ── Pin Definitions ──────────────────────────
const int RELAY_PINS[]  = {4, 5, 6, 7};  // Relay output pins
const int NUM_RELAYS    = 4;
const int STATUS_LED    = 13;

// ── Configuration ────────────────────────────
const bool RELAY_ACTIVE_LOW = true;  // Most relay modules are active-low

// ── State Variables ──────────────────────────
bool relayStates[4] = {false, false, false, false};
unsigned long relayTimers[4] = {0, 0, 0, 0}; // Auto-off timers
String relayNames[4] = {"Light", "Fan", "Heater", "Pump"};

void setup() {
  Serial.begin(9600);
  pinMode(STATUS_LED, OUTPUT);

  for (int i = 0; i < NUM_RELAYS; i++) {
    pinMode(RELAY_PINS[i], OUTPUT);
    setRelay(i, false);  // All off at startup
  }

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║   EE ZONE Relay Controller v1.0     ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("Commands:"));
  Serial.println(F("  ON <ch>          - Turn on relay (1-4)"));
  Serial.println(F("  OFF <ch>         - Turn off relay (1-4)"));
  Serial.println(F("  TOGGLE <ch>      - Toggle relay"));
  Serial.println(F("  TIMER <ch> <sec> - Auto-off timer"));
  Serial.println(F("  STATUS           - Show all states"));
  Serial.println(F("  ALLOFF           - Emergency all off"));
  Serial.println(F("────────────────────────────────────────"));
  printStatus();
}

void loop() {
  // Check auto-off timers
  for (int i = 0; i < NUM_RELAYS; i++) {
    if (relayTimers[i] > 0 && millis() >= relayTimers[i]) {
      setRelay(i, false);
      relayTimers[i] = 0;
      Serial.print(F("⏱ Timer expired: "));
      Serial.print(relayNames[i]);
      Serial.println(F(" → OFF"));
    }
  }

  // Handle serial commands
  if (Serial.available()) {
    String cmd = Serial.readStringUntil('\\n');
    cmd.trim();
    cmd.toUpperCase();
    processCommand(cmd);
  }

  // Status LED blink if any relay is on
  bool anyOn = false;
  for (int i = 0; i < NUM_RELAYS; i++) {
    if (relayStates[i]) { anyOn = true; break; }
  }
  digitalWrite(STATUS_LED, anyOn ? HIGH : LOW);
}

void processCommand(String cmd) {
  if (cmd.startsWith("ON ")) {
    int ch = cmd.substring(3).toInt() - 1;
    if (validChannel(ch)) {
      setRelay(ch, true);
      Serial.print(relayNames[ch]);
      Serial.println(F(" → ON"));
    }
  } else if (cmd.startsWith("OFF ")) {
    int ch = cmd.substring(4).toInt() - 1;
    if (validChannel(ch)) {
      setRelay(ch, false);
      relayTimers[ch] = 0;
      Serial.print(relayNames[ch]);
      Serial.println(F(" → OFF"));
    }
  } else if (cmd.startsWith("TOGGLE ")) {
    int ch = cmd.substring(7).toInt() - 1;
    if (validChannel(ch)) {
      setRelay(ch, !relayStates[ch]);
      Serial.print(relayNames[ch]);
      Serial.print(F(" → "));
      Serial.println(relayStates[ch] ? "ON" : "OFF");
    }
  } else if (cmd.startsWith("TIMER ")) {
    int spaceIdx = cmd.indexOf(' ', 6);
    if (spaceIdx > 0) {
      int ch = cmd.substring(6, spaceIdx).toInt() - 1;
      int secs = cmd.substring(spaceIdx + 1).toInt();
      if (validChannel(ch) && secs > 0) {
        setRelay(ch, true);
        relayTimers[ch] = millis() + (unsigned long)secs * 1000;
        Serial.print(relayNames[ch]);
        Serial.print(F(" → ON for "));
        Serial.print(secs);
        Serial.println(F(" seconds"));
      }
    }
  } else if (cmd == "STATUS") {
    printStatus();
  } else if (cmd == "ALLOFF") {
    for (int i = 0; i < NUM_RELAYS; i++) {
      setRelay(i, false);
      relayTimers[i] = 0;
    }
    Serial.println(F("🛑 ALL RELAYS OFF"));
  }
}

void setRelay(int ch, bool state) {
  relayStates[ch] = state;
  if (RELAY_ACTIVE_LOW) {
    digitalWrite(RELAY_PINS[ch], state ? LOW : HIGH);
  } else {
    digitalWrite(RELAY_PINS[ch], state ? HIGH : LOW);
  }
}

bool validChannel(int ch) {
  if (ch < 0 || ch >= NUM_RELAYS) {
    Serial.println(F("[ERROR] Invalid channel (use 1-4)"));
    return false;
  }
  return true;
}

void printStatus() {
  Serial.println(F("── Relay Status ──"));
  for (int i = 0; i < NUM_RELAYS; i++) {
    Serial.print(F("  ["));
    Serial.print(i + 1);
    Serial.print(F("] "));
    Serial.print(relayNames[i]);
    Serial.print(F(": "));
    Serial.print(relayStates[i] ? "ON " : "OFF");
    if (relayTimers[i] > 0) {
      long remaining = (relayTimers[i] - millis()) / 1000;
      Serial.print(F("  (auto-off in "));
      Serial.print(remaining);
      Serial.print(F("s)"));
    }
    Serial.println();
  }
}`
  },
  {
    keywords: ['button', 'push', 'debounce', 'press', 'input', 'switch', 'toggle'],
    title: 'Button Debounce Controller',
    description: 'Multi-button input with debouncing and press detection',
    code: `/*
 * Multi-Button Input Handler with Debounce
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Handles multiple buttons with debouncing,
 * short press, long press, and double-click detection.
 */

// ── Pin Definitions ──────────────────────────
const int BUTTON_PINS[] = {2, 3, 4, 5};
const int LED_PINS[]    = {8, 9, 10, 11};
const int NUM_BUTTONS   = 4;

// ── Debounce Configuration ───────────────────
const unsigned long DEBOUNCE_DELAY   = 50;    // ms
const unsigned long LONG_PRESS_TIME  = 1000;  // ms
const unsigned long DOUBLE_CLICK_GAP = 300;   // ms

// ── State Variables ──────────────────────────
struct ButtonState {
  bool currentState;
  bool lastState;
  bool ledState;
  unsigned long lastDebounceTime;
  unsigned long pressStartTime;
  unsigned long lastClickTime;
  int clickCount;
  bool longPressTriggered;
};

ButtonState buttons[4];

void setup() {
  Serial.begin(9600);

  for (int i = 0; i < NUM_BUTTONS; i++) {
    pinMode(BUTTON_PINS[i], INPUT_PULLUP);
    pinMode(LED_PINS[i], OUTPUT);
    buttons[i] = {HIGH, HIGH, false, 0, 0, 0, 0, false};
  }

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║   EE ZONE Button Handler v1.0       ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("Press buttons for: short, long, double-click"));
}

void loop() {
  for (int i = 0; i < NUM_BUTTONS; i++) {
    processButton(i);
  }
}

void processButton(int idx) {
  bool reading = digitalRead(BUTTON_PINS[idx]);
  unsigned long now = millis();

  // Debounce
  if (reading != buttons[idx].lastState) {
    buttons[idx].lastDebounceTime = now;
  }

  if ((now - buttons[idx].lastDebounceTime) > DEBOUNCE_DELAY) {
    if (reading != buttons[idx].currentState) {
      buttons[idx].currentState = reading;

      if (buttons[idx].currentState == LOW) {  // Button pressed
        buttons[idx].pressStartTime = now;
        buttons[idx].longPressTriggered = false;
      }

      if (buttons[idx].currentState == HIGH) {  // Button released
        if (!buttons[idx].longPressTriggered) {
          // Check for double-click
          if ((now - buttons[idx].lastClickTime) < DOUBLE_CLICK_GAP) {
            buttons[idx].clickCount++;
          } else {
            buttons[idx].clickCount = 1;
          }
          buttons[idx].lastClickTime = now;
        }
      }
    }
  }

  // Long press detection (while held)
  if (buttons[idx].currentState == LOW && !buttons[idx].longPressTriggered) {
    if ((now - buttons[idx].pressStartTime) > LONG_PRESS_TIME) {
      buttons[idx].longPressTriggered = true;
      onLongPress(idx);
    }
  }

  // Process clicks after gap
  if (buttons[idx].clickCount > 0 &&
      (now - buttons[idx].lastClickTime) > DOUBLE_CLICK_GAP) {
    if (buttons[idx].clickCount == 1) {
      onSingleClick(idx);
    } else if (buttons[idx].clickCount >= 2) {
      onDoubleClick(idx);
    }
    buttons[idx].clickCount = 0;
  }

  buttons[idx].lastState = reading;
}

void onSingleClick(int idx) {
  buttons[idx].ledState = !buttons[idx].ledState;
  digitalWrite(LED_PINS[idx], buttons[idx].ledState);
  Serial.print(F("Button "));
  Serial.print(idx + 1);
  Serial.print(F(": CLICK → LED "));
  Serial.println(buttons[idx].ledState ? "ON" : "OFF");
}

void onDoubleClick(int idx) {
  // Flash LED rapidly
  for (int i = 0; i < 6; i++) {
    digitalWrite(LED_PINS[idx], i % 2);
    delay(80);
  }
  Serial.print(F("Button "));
  Serial.print(idx + 1);
  Serial.println(F(": DOUBLE-CLICK → Flash"));
}

void onLongPress(int idx) {
  // Turn off all LEDs
  for (int i = 0; i < NUM_BUTTONS; i++) {
    buttons[i].ledState = false;
    digitalWrite(LED_PINS[i], LOW);
  }
  Serial.print(F("Button "));
  Serial.print(idx + 1);
  Serial.println(F(": LONG PRESS → All LEDs OFF"));
}`
  },
  {
    keywords: ['ir', 'infrared', 'remote', 'receiver', 'tv remote'],
    title: 'IR Remote Receiver',
    description: 'Decode and respond to IR remote control signals',
    code: `/*
 * IR Remote Control Receiver
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Receives and decodes infrared remote control signals.
 * Controls LEDs and relays based on button presses.
 */

#include <IRremote.h>

// ── Pin Definitions ──────────────────────────
const int IR_RECV_PIN  = 11;
const int LED_PINS[]   = {3, 4, 5, 6};
const int NUM_LEDS     = 4;

// ── Common NEC Remote Button Codes ───────────
#define BTN_POWER    0xFFA25D
#define BTN_1        0xFF6897
#define BTN_2        0xFF9867
#define BTN_3        0xFFB04F
#define BTN_4        0xFF30CF
#define BTN_UP       0xFF18E7
#define BTN_DOWN     0xFF4AB5
#define BTN_OK       0xFF38C7

// ── State ────────────────────────────────────
bool ledStates[4] = {false, false, false, false};
int  brightness = 128;

void setup() {
  Serial.begin(9600);
  IrReceiver.begin(IR_RECV_PIN);

  for (int i = 0; i < NUM_LEDS; i++) {
    pinMode(LED_PINS[i], OUTPUT);
    digitalWrite(LED_PINS[i], LOW);
  }

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║   EE ZONE IR Remote Receiver v1.0   ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("Point your remote at the IR receiver."));
}

void loop() {
  if (IrReceiver.decode()) {
    unsigned long code = IrReceiver.decodedIRData.decodedRawData;

    Serial.print(F("IR Code: 0x"));
    Serial.println(code, HEX);

    handleIRCode(code);
    IrReceiver.resume();
  }
}

void handleIRCode(unsigned long code) {
  switch (code) {
    case BTN_POWER:
      // Toggle all LEDs
      {
        bool allOff = true;
        for (int i = 0; i < NUM_LEDS; i++) if (ledStates[i]) allOff = false;
        for (int i = 0; i < NUM_LEDS; i++) {
          ledStates[i] = allOff;
          digitalWrite(LED_PINS[i], ledStates[i]);
        }
        Serial.println(allOff ? F("All LEDs ON") : F("All LEDs OFF"));
      }
      break;
    case BTN_1: toggleLED(0); break;
    case BTN_2: toggleLED(1); break;
    case BTN_3: toggleLED(2); break;
    case BTN_4: toggleLED(3); break;
    case BTN_UP:
      brightness = min(255, brightness + 25);
      updateBrightness();
      break;
    case BTN_DOWN:
      brightness = max(0, brightness - 25);
      updateBrightness();
      break;
    default:
      Serial.println(F("Unknown button"));
      break;
  }
}

void toggleLED(int idx) {
  if (idx >= NUM_LEDS) return;
  ledStates[idx] = !ledStates[idx];
  digitalWrite(LED_PINS[idx], ledStates[idx]);
  Serial.print(F("LED "));
  Serial.print(idx + 1);
  Serial.print(F(": "));
  Serial.println(ledStates[idx] ? "ON" : "OFF");
}

void updateBrightness() {
  for (int i = 0; i < NUM_LEDS; i++) {
    if (ledStates[i]) {
      analogWrite(LED_PINS[i], brightness);
    }
  }
  Serial.print(F("Brightness: "));
  Serial.print(map(brightness, 0, 255, 0, 100));
  Serial.println(F("%"));
}`
  },
  {
    keywords: ['stepper', 'step motor', 'nema', 'a4988', 'drv8825', 'cnc', 'position'],
    title: 'Stepper Motor Controller',
    description: 'A4988/DRV8825 stepper motor control with acceleration',
    code: `/*
 * Stepper Motor Controller with Acceleration
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Controls a stepper motor via A4988/DRV8825 driver.
 * Features: acceleration, position tracking, serial commands.
 */

// ── Pin Definitions ──────────────────────────
const int STEP_PIN = 3;
const int DIR_PIN  = 4;
const int EN_PIN   = 5;
const int MS1_PIN  = 6;
const int MS2_PIN  = 7;
const int MS3_PIN  = 8;

// ── Motor Configuration ─────────────────────
const int   STEPS_PER_REV    = 200;   // 1.8° per step
const int   MICROSTEP_FACTOR = 16;    // Microstepping
const float MAX_SPEED_RPM    = 100.0;
const float ACCEL_STEPS_S2   = 500.0; // Steps/sec²

// ── Variables ────────────────────────────────
long currentPosition = 0;
long targetPosition  = 0;
float currentSpeed   = 0;
bool motorEnabled    = false;

void setup() {
  Serial.begin(9600);

  pinMode(STEP_PIN, OUTPUT);
  pinMode(DIR_PIN, OUTPUT);
  pinMode(EN_PIN, OUTPUT);
  pinMode(MS1_PIN, OUTPUT);
  pinMode(MS2_PIN, OUTPUT);
  pinMode(MS3_PIN, OUTPUT);

  // Set 1/16 microstepping
  digitalWrite(MS1_PIN, HIGH);
  digitalWrite(MS2_PIN, HIGH);
  digitalWrite(MS3_PIN, HIGH);

  disableMotor();

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║  EE ZONE Stepper Controller v1.0    ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("Commands:"));
  Serial.println(F("  MOVE <steps>  - Relative move"));
  Serial.println(F("  GOTO <pos>    - Absolute move"));
  Serial.println(F("  HOME          - Return to zero"));
  Serial.println(F("  POS           - Show position"));
  Serial.println(F("  ENABLE/DISABLE"));
}

void loop() {
  if (Serial.available()) {
    String cmd = Serial.readStringUntil('\\n');
    cmd.trim();
    cmd.toUpperCase();
    processCommand(cmd);
  }
}

void processCommand(String cmd) {
  if (cmd.startsWith("MOVE ")) {
    long steps = cmd.substring(5).toInt();
    enableMotor();
    moveSteps(steps);
    Serial.print(F("Moved "));
    Serial.print(steps);
    Serial.print(F(" steps. Position: "));
    Serial.println(currentPosition);
  } else if (cmd.startsWith("GOTO ")) {
    long pos = cmd.substring(5).toInt();
    enableMotor();
    long steps = pos - currentPosition;
    moveSteps(steps);
    Serial.print(F("At position: "));
    Serial.println(currentPosition);
  } else if (cmd == "HOME") {
    enableMotor();
    moveSteps(-currentPosition);
    Serial.println(F("Homed to position 0"));
  } else if (cmd == "POS") {
    Serial.print(F("Position: "));
    Serial.println(currentPosition);
  } else if (cmd == "ENABLE") {
    enableMotor();
  } else if (cmd == "DISABLE") {
    disableMotor();
  }
}

void moveSteps(long steps) {
  if (steps == 0) return;

  bool dir = steps > 0;
  digitalWrite(DIR_PIN, dir ? HIGH : LOW);
  long absSteps = abs(steps);

  // Calculate timing for acceleration profile
  long accelSteps = absSteps / 3;  // 1/3 accel, 1/3 cruise, 1/3 decel
  float maxStepDelay = 1000000.0 / (MAX_SPEED_RPM * STEPS_PER_REV * MICROSTEP_FACTOR / 60.0);
  float startDelay = maxStepDelay * 5;  // Start slow

  for (long i = 0; i < absSteps; i++) {
    float delay_us;

    if (i < accelSteps) {
      // Accelerating
      delay_us = startDelay - (startDelay - maxStepDelay) * ((float)i / accelSteps);
    } else if (i > absSteps - accelSteps) {
      // Decelerating
      long decelStep = absSteps - i;
      delay_us = startDelay - (startDelay - maxStepDelay) * ((float)decelStep / accelSteps);
    } else {
      // Cruising
      delay_us = maxStepDelay;
    }

    digitalWrite(STEP_PIN, HIGH);
    delayMicroseconds(max(2, (int)(delay_us / 2)));
    digitalWrite(STEP_PIN, LOW);
    delayMicroseconds(max(2, (int)(delay_us / 2)));

    currentPosition += dir ? 1 : -1;
  }
}

void enableMotor() {
  digitalWrite(EN_PIN, LOW);  // Active-low enable
  motorEnabled = true;
  Serial.println(F("Motor ENABLED"));
}

void disableMotor() {
  digitalWrite(EN_PIN, HIGH);
  motorEnabled = false;
  Serial.println(F("Motor DISABLED"));
}`
  },
  {
    keywords: ['keypad', 'password', 'lock', 'access', 'security', 'pin code', '4x4', '3x4'],
    title: 'Keypad Access System',
    description: 'Security keypad with password protection and lock control',
    code: `/*
 * Keypad-based Access Control System
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * 4x4 keypad password entry with lock control,
 * LED feedback, buzzer alerts, and lockout protection.
 */

#include <Keypad.h>

// ── Keypad Configuration ─────────────────────
const byte ROWS = 4;
const byte COLS = 4;
char keys[ROWS][COLS] = {
  {'1','2','3','A'},
  {'4','5','6','B'},
  {'7','8','9','C'},
  {'*','0','#','D'}
};
byte rowPins[ROWS] = {9, 8, 7, 6};
byte colPins[COLS] = {5, 4, 3, 2};
Keypad keypad = Keypad(makeKeymap(keys), rowPins, colPins, ROWS, COLS);

// ── Pin Definitions ──────────────────────────
const int LOCK_PIN     = 10;  // Solenoid / electric lock
const int GREEN_LED    = 11;
const int RED_LED      = 12;
const int BUZZER_PIN   = 13;

// ── Security Configuration ───────────────────
const char PASSWORD[]  = "1234A";
const int  MAX_ATTEMPTS = 3;
const unsigned long LOCKOUT_TIME = 30000;  // 30 seconds

// ── State Variables ──────────────────────────
char inputBuffer[10] = "";
int  bufferIndex     = 0;
int  failedAttempts  = 0;
bool isLocked        = true;
bool isLockedOut     = false;
unsigned long lockoutStart = 0;
unsigned long unlockTime   = 0;

void setup() {
  Serial.begin(9600);
  pinMode(LOCK_PIN, OUTPUT);
  pinMode(GREEN_LED, OUTPUT);
  pinMode(RED_LED, OUTPUT);
  pinMode(BUZZER_PIN, OUTPUT);

  lockDoor();

  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║   EE ZONE Access Control v1.0       ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("Enter password + # to unlock"));
  Serial.println(F("Press * to clear input"));
}

void loop() {
  // Check lockout timer
  if (isLockedOut && (millis() - lockoutStart >= LOCKOUT_TIME)) {
    isLockedOut = false;
    failedAttempts = 0;
    Serial.println(F("Lockout ended. Try again."));
    digitalWrite(RED_LED, LOW);
  }

  // Auto-relock after 5 seconds
  if (!isLocked && millis() >= unlockTime) {
    lockDoor();
    Serial.println(F("Auto-locked."));
  }

  char key = keypad.getKey();
  if (!key) return;

  if (isLockedOut) {
    tone(BUZZER_PIN, 200, 200);
    Serial.println(F("LOCKED OUT! Wait..."));
    return;
  }

  tone(BUZZER_PIN, 1200, 50);  // Key press feedback

  if (key == '*') {
    // Clear input
    bufferIndex = 0;
    inputBuffer[0] = '\\0';
    Serial.println(F("Input cleared."));
  } else if (key == '#') {
    // Submit password
    inputBuffer[bufferIndex] = '\\0';
    checkPassword();
    bufferIndex = 0;
    inputBuffer[0] = '\\0';
  } else {
    if (bufferIndex < 9) {
      inputBuffer[bufferIndex++] = key;
      inputBuffer[bufferIndex] = '\\0';
      Serial.print(F("*"));  // Mask input
    }
  }
}

void checkPassword() {
  Serial.println();
  if (strcmp(inputBuffer, PASSWORD) == 0) {
    unlockDoor();
    failedAttempts = 0;
    Serial.println(F("✓ ACCESS GRANTED"));
  } else {
    failedAttempts++;
    Serial.print(F("✗ WRONG PASSWORD ("));
    Serial.print(failedAttempts);
    Serial.print(F("/"));
    Serial.print(MAX_ATTEMPTS);
    Serial.println(F(")"));

    // Error beep
    for (int i = 0; i < 3; i++) {
      tone(BUZZER_PIN, 400, 100);
      delay(150);
    }

    flashLED(RED_LED, 3, 200);

    if (failedAttempts >= MAX_ATTEMPTS) {
      isLockedOut = true;
      lockoutStart = millis();
      Serial.println(F("⚠ LOCKED OUT for 30 seconds!"));
      tone(BUZZER_PIN, 300, 2000);
      digitalWrite(RED_LED, HIGH);
    }
  }
}

void unlockDoor() {
  isLocked = false;
  digitalWrite(LOCK_PIN, HIGH);
  digitalWrite(GREEN_LED, HIGH);
  digitalWrite(RED_LED, LOW);
  tone(BUZZER_PIN, 2000, 200);
  delay(200);
  tone(BUZZER_PIN, 2500, 200);
  unlockTime = millis() + 5000;  // Auto-lock in 5s
}

void lockDoor() {
  isLocked = true;
  digitalWrite(LOCK_PIN, LOW);
  digitalWrite(GREEN_LED, LOW);
  digitalWrite(RED_LED, LOW);
}

void flashLED(int pin, int times, int delayMs) {
  for (int i = 0; i < times; i++) {
    digitalWrite(pin, HIGH);
    delay(delayMs);
    digitalWrite(pin, LOW);
    delay(delayMs);
  }
}`
  }
];

// ─── ESP32 TEMPLATES ────────────────────────────────────────────────

const esp32Templates: CodeTemplate[] = [
  {
    keywords: ['wifi', 'web', 'server', 'iot', 'http', 'dashboard', 'webpage', 'monitor'],
    title: 'WiFi Web Server Dashboard',
    description: 'ESP32 web server with real-time sensor dashboard',
    code: `/*
 * ESP32 WiFi Web Server Dashboard
 * Platform: ESP32
 * Generated by EE ZONE AI Code Assistant
 *
 * Creates a WiFi web server with a real-time dashboard
 * showing sensor data, GPIO control, and system info.
 */

#include <WiFi.h>
#include <WebServer.h>

// ── WiFi Configuration ───────────────────────
const char* ssid     = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

// ── Pin Definitions ──────────────────────────
const int LED_PIN       = 2;    // Built-in LED
const int RELAY_PIN     = 4;    // Relay output
const int SENSOR_PIN    = 34;   // Analog sensor input
const int TEMP_PIN      = 35;   // Temperature sensor

// ── Web Server ───────────────────────────────
WebServer server(80);

// ── State Variables ──────────────────────────
bool relayState = false;
float sensorValue = 0;
float temperature = 0;
unsigned long uptime = 0;

void setup() {
  Serial.begin(115200);

  pinMode(LED_PIN, OUTPUT);
  pinMode(RELAY_PIN, OUTPUT);
  pinMode(SENSOR_PIN, INPUT);
  pinMode(TEMP_PIN, INPUT);

  digitalWrite(RELAY_PIN, LOW);

  // Connect to WiFi
  Serial.print("Connecting to WiFi");
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    digitalWrite(LED_PIN, !digitalRead(LED_PIN));
  }
  Serial.println();
  Serial.print("Connected! IP: ");
  Serial.println(WiFi.localIP());
  digitalWrite(LED_PIN, HIGH);

  // Setup routes
  server.on("/", handleRoot);
  server.on("/api/data", handleData);
  server.on("/api/relay/on", handleRelayOn);
  server.on("/api/relay/off", handleRelayOff);
  server.on("/api/relay/toggle", handleRelayToggle);
  server.begin();

  Serial.println("EE ZONE ESP32 Dashboard Ready!");
}

void loop() {
  server.handleClient();
  readSensors();
  delay(10);
}

void readSensors() {
  static unsigned long lastRead = 0;
  if (millis() - lastRead < 1000) return;
  lastRead = millis();

  int rawSensor = analogRead(SENSOR_PIN);
  sensorValue = (rawSensor / 4095.0) * 100.0;

  int rawTemp = analogRead(TEMP_PIN);
  temperature = (rawTemp / 4095.0) * 330.0 - 50.0; // LM35 approximate

  uptime = millis() / 1000;
}

void handleRelayOn() {
  relayState = true;
  digitalWrite(RELAY_PIN, HIGH);
  server.send(200, "application/json", "{\\"relay\\":true}");
}

void handleRelayOff() {
  relayState = false;
  digitalWrite(RELAY_PIN, LOW);
  server.send(200, "application/json", "{\\"relay\\":false}");
}

void handleRelayToggle() {
  relayState = !relayState;
  digitalWrite(RELAY_PIN, relayState ? HIGH : LOW);
  String json = "{\\"relay\\":" + String(relayState ? "true" : "false") + "}";
  server.send(200, "application/json", json);
}

void handleData() {
  String json = "{"
    "\\"temperature\\":" + String(temperature, 1) + ","
    "\\"sensor\\":" + String(sensorValue, 1) + ","
    "\\"relay\\":" + String(relayState ? "true" : "false") + ","
    "\\"uptime\\":" + String(uptime) + ","
    "\\"rssi\\":" + String(WiFi.RSSI()) + ","
    "\\"ip\\":\\"" + WiFi.localIP().toString() + "\\""
  "}";
  server.send(200, "application/json", json);
}

void handleRoot() {
  String html = R"rawliteral(
<!DOCTYPE html>
<html>
<head>
  <title>EE ZONE ESP32 Dashboard</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:'Segoe UI',sans-serif; background:#0a0a1a; color:#fff; padding:20px; }
    h1 { text-align:center; color:#9C4AFF; margin-bottom:20px; }
    .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:15px; max-width:800px; margin:0 auto; }
    .card { background:rgba(156,74,255,0.1); border:1px solid rgba(156,74,255,0.3); border-radius:12px; padding:20px; text-align:center; }
    .card .label { color:#B8A7E0; font-size:0.85em; margin-bottom:8px; }
    .card .value { font-size:2em; font-weight:bold; color:#FF00C8; }
    .card .unit { font-size:0.5em; color:#B8A7E0; }
    .btn { background:linear-gradient(135deg,#9C4AFF,#FF00C8); border:none; color:#fff; padding:12px 24px; border-radius:8px; cursor:pointer; font-size:1em; margin:5px; }
    .btn:hover { opacity:0.8; }
    .btn.off { background:rgba(255,0,0,0.3); border:1px solid rgba(255,0,0,0.5); }
    .controls { text-align:center; margin:20px 0; }
  </style>
</head>
<body>
  <h1>⚡ EE ZONE Dashboard</h1>
  <div class='grid'>
    <div class='card'><div class='label'>Temperature</div><div class='value' id='temp'>--<span class='unit'> °C</span></div></div>
    <div class='card'><div class='label'>Sensor</div><div class='value' id='sensor'>--<span class='unit'> %</span></div></div>
    <div class='card'><div class='label'>WiFi Signal</div><div class='value' id='rssi'>--<span class='unit'> dBm</span></div></div>
    <div class='card'><div class='label'>Uptime</div><div class='value' id='uptime'>--<span class='unit'> s</span></div></div>
  </div>
  <div class='controls'>
    <h2 style='color:#B8A7E0;margin:15px 0'>Relay Control</h2>
    <button class='btn' onclick='toggleRelay()' id='relayBtn'>Toggle Relay</button>
    <p style='color:#B8A7E0;margin-top:10px'>Status: <span id='relayStatus' style='color:#FF00C8'>OFF</span></p>
  </div>
  <script>
    function fetchData(){
      fetch('/api/data').then(r=>r.json()).then(d=>{
        document.getElementById('temp').innerHTML=d.temperature.toFixed(1)+'<span class="unit"> °C</span>';
        document.getElementById('sensor').innerHTML=d.sensor.toFixed(1)+'<span class="unit"> %</span>';
        document.getElementById('rssi').innerHTML=d.rssi+'<span class="unit"> dBm</span>';
        document.getElementById('uptime').innerHTML=d.uptime+'<span class="unit"> s</span>';
        document.getElementById('relayStatus').textContent=d.relay?'ON':'OFF';
        document.getElementById('relayStatus').style.color=d.relay?'#00ff88':'#FF00C8';
      });
    }
    function toggleRelay(){ fetch('/api/relay/toggle').then(()=>fetchData()); }
    setInterval(fetchData, 2000);
    fetchData();
  </script>
</body>
</html>
)rawliteral";
  server.send(200, "text/html", html);
}`
  },
  {
    keywords: ['bluetooth', 'ble', 'mobile', 'phone', 'app', 'wireless'],
    title: 'Bluetooth Low Energy Controller',
    description: 'BLE serial communication with mobile app control',
    code: `/*
 * ESP32 Bluetooth Low Energy (BLE) Controller
 * Platform: ESP32
 * Generated by EE ZONE AI Code Assistant
 *
 * Creates a BLE UART service for wireless communication
 * with smartphones. Controls GPIOs via BLE commands.
 */

#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>

// ── BLE Configuration ────────────────────────
#define SERVICE_UUID        "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
#define CHAR_RX_UUID        "6E400002-B5A3-F393-E0A9-E50E24DCCA9E"
#define CHAR_TX_UUID        "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"
#define DEVICE_NAME         "EE-ZONE-ESP32"

// ── Pin Definitions ──────────────────────────
const int LED_PIN    = 2;
const int RELAY_PINS[] = {4, 5, 18, 19};
const int NUM_RELAYS = 4;

// ── State ────────────────────────────────────
BLEServer *pServer = NULL;
BLECharacteristic *pTxCharacteristic;
bool deviceConnected = false;
bool relayStates[4] = {false, false, false, false};

// ── BLE Callbacks ────────────────────────────
class ServerCallbacks : public BLEServerCallbacks {
  void onConnect(BLEServer* pServer) {
    deviceConnected = true;
    Serial.println("BLE Client Connected!");
    sendBLE("EE ZONE ESP32 Ready!\\n");
    sendStatus();
  }

  void onDisconnect(BLEServer* pServer) {
    deviceConnected = false;
    Serial.println("BLE Client Disconnected");
    delay(500);
    pServer->startAdvertising();
  }
};

class RxCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic *pCharacteristic) {
    String rxValue = pCharacteristic->getValue().c_str();
    if (rxValue.length() > 0) {
      rxValue.trim();
      Serial.print("BLE RX: ");
      Serial.println(rxValue);
      processCommand(rxValue);
    }
  }
};

void setup() {
  Serial.begin(115200);

  // Setup GPIO
  pinMode(LED_PIN, OUTPUT);
  for (int i = 0; i < NUM_RELAYS; i++) {
    pinMode(RELAY_PINS[i], OUTPUT);
    digitalWrite(RELAY_PINS[i], LOW);
  }

  // Initialize BLE
  BLEDevice::init(DEVICE_NAME);
  pServer = BLEDevice::createServer();
  pServer->setCallbacks(new ServerCallbacks());

  BLEService *pService = pServer->createService(SERVICE_UUID);

  pTxCharacteristic = pService->createCharacteristic(
    CHAR_TX_UUID, BLECharacteristic::PROPERTY_NOTIFY
  );
  pTxCharacteristic->addDescriptor(new BLE2902());

  BLECharacteristic *pRxCharacteristic = pService->createCharacteristic(
    CHAR_RX_UUID, BLECharacteristic::PROPERTY_WRITE
  );
  pRxCharacteristic->setCallbacks(new RxCallbacks());

  pService->start();

  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);
  pAdvertising->setScanResponse(true);
  pAdvertising->start();

  Serial.println("EE ZONE BLE Controller Ready!");
  Serial.print("Device name: ");
  Serial.println(DEVICE_NAME);
}

void loop() {
  // Heartbeat LED
  static unsigned long lastBlink = 0;
  if (millis() - lastBlink > (deviceConnected ? 1000 : 250)) {
    lastBlink = millis();
    digitalWrite(LED_PIN, !digitalRead(LED_PIN));
  }

  // Send periodic sensor data if connected
  static unsigned long lastSend = 0;
  if (deviceConnected && millis() - lastSend > 5000) {
    lastSend = millis();
    int sensor = analogRead(36);
    String msg = "SENSOR:" + String(sensor) + "\\n";
    sendBLE(msg);
  }
}

void sendBLE(String msg) {
  if (deviceConnected) {
    pTxCharacteristic->setValue(msg.c_str());
    pTxCharacteristic->notify();
  }
}

void processCommand(String cmd) {
  cmd.toUpperCase();

  if (cmd.startsWith("ON ")) {
    int ch = cmd.substring(3).toInt() - 1;
    if (ch >= 0 && ch < NUM_RELAYS) {
      relayStates[ch] = true;
      digitalWrite(RELAY_PINS[ch], HIGH);
      sendBLE("Relay " + String(ch + 1) + " ON\\n");
    }
  } else if (cmd.startsWith("OFF ")) {
    int ch = cmd.substring(4).toInt() - 1;
    if (ch >= 0 && ch < NUM_RELAYS) {
      relayStates[ch] = false;
      digitalWrite(RELAY_PINS[ch], LOW);
      sendBLE("Relay " + String(ch + 1) + " OFF\\n");
    }
  } else if (cmd == "STATUS") {
    sendStatus();
  } else if (cmd == "ALLOFF") {
    for (int i = 0; i < NUM_RELAYS; i++) {
      relayStates[i] = false;
      digitalWrite(RELAY_PINS[i], LOW);
    }
    sendBLE("All relays OFF\\n");
  } else {
    sendBLE("Unknown cmd: " + cmd + "\\n");
  }
}

void sendStatus() {
  String status = "── Status ──\\n";
  for (int i = 0; i < NUM_RELAYS; i++) {
    status += "R" + String(i + 1) + ": " + (relayStates[i] ? "ON" : "OFF") + "\\n";
  }
  status += "RSSI: " + String(WiFi.RSSI()) + " dBm\\n";
  sendBLE(status);
}`
  },
  {
    keywords: ['mqtt', 'cloud', 'publish', 'subscribe', 'broker', 'smart home', 'home assistant'],
    title: 'MQTT IoT Client',
    description: 'MQTT publish/subscribe IoT device for smart home',
    code: `/*
 * ESP32 MQTT IoT Client
 * Platform: ESP32
 * Generated by EE ZONE AI Code Assistant
 *
 * Connects to WiFi and MQTT broker for IoT communication.
 * Publishes sensor data and subscribes to control commands.
 * Compatible with Home Assistant, Node-RED, etc.
 */

#include <WiFi.h>
#include <PubSubClient.h>

// ── WiFi Configuration ───────────────────────
const char* wifi_ssid     = "YOUR_WIFI_SSID";
const char* wifi_password = "YOUR_WIFI_PASSWORD";

// ── MQTT Configuration ───────────────────────
const char* mqtt_server   = "YOUR_MQTT_BROKER_IP";
const int   mqtt_port     = 1883;
const char* mqtt_user     = "";  // Leave empty if no auth
const char* mqtt_password = "";
const char* client_id     = "eezone-esp32-001";

// ── MQTT Topics ──────────────────────────────
#define TOPIC_TEMP     "eezone/sensor/temperature"
#define TOPIC_HUMIDITY "eezone/sensor/humidity"
#define TOPIC_RELAY    "eezone/relay/set"
#define TOPIC_STATUS   "eezone/status"
#define TOPIC_RELAY_STATE "eezone/relay/state"

// ── Pin Definitions ──────────────────────────
const int LED_PIN    = 2;
const int RELAY_PIN  = 4;
const int SENSOR_PIN = 34;

// ── Objects ──────────────────────────────────
WiFiClient espClient;
PubSubClient mqtt(espClient);

// ── State ────────────────────────────────────
bool relayState = false;
unsigned long lastPublish = 0;
const unsigned long PUBLISH_INTERVAL = 10000; // 10 seconds

void setup() {
  Serial.begin(115200);

  pinMode(LED_PIN, OUTPUT);
  pinMode(RELAY_PIN, OUTPUT);
  digitalWrite(RELAY_PIN, LOW);

  connectWiFi();

  mqtt.setServer(mqtt_server, mqtt_port);
  mqtt.setCallback(mqttCallback);

  Serial.println("EE ZONE MQTT Client Ready!");
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    connectWiFi();
  }

  if (!mqtt.connected()) {
    connectMQTT();
  }

  mqtt.loop();

  // Publish sensor data periodically
  if (millis() - lastPublish > PUBLISH_INTERVAL) {
    lastPublish = millis();
    publishSensorData();
  }
}

void connectWiFi() {
  Serial.print("Connecting to WiFi...");
  WiFi.begin(wifi_ssid, wifi_password);
  int attempts = 0;
  while (WiFi.status() != WL_CONNECTED && attempts < 20) {
    delay(500);
    Serial.print(".");
    attempts++;
  }
  if (WiFi.status() == WL_CONNECTED) {
    Serial.println(" Connected!");
    Serial.print("IP: ");
    Serial.println(WiFi.localIP());
  } else {
    Serial.println(" Failed!");
  }
}

void connectMQTT() {
  while (!mqtt.connected()) {
    Serial.print("Connecting to MQTT...");

    bool connected;
    if (strlen(mqtt_user) > 0) {
      connected = mqtt.connect(client_id, mqtt_user, mqtt_password);
    } else {
      connected = mqtt.connect(client_id);
    }

    if (connected) {
      Serial.println(" Connected!");

      // Subscribe to control topics
      mqtt.subscribe(TOPIC_RELAY);

      // Publish online status
      mqtt.publish(TOPIC_STATUS, "online", true);

      // Publish current relay state
      mqtt.publish(TOPIC_RELAY_STATE, relayState ? "ON" : "OFF", true);

      digitalWrite(LED_PIN, HIGH);
    } else {
      Serial.print(" Failed (rc=");
      Serial.print(mqtt.state());
      Serial.println("), retrying in 5s...");
      delay(5000);
    }
  }
}

void mqttCallback(char* topic, byte* payload, unsigned int length) {
  String message;
  for (unsigned int i = 0; i < length; i++) {
    message += (char)payload[i];
  }
  message.trim();
  message.toUpperCase();

  Serial.print("MQTT [");
  Serial.print(topic);
  Serial.print("]: ");
  Serial.println(message);

  if (String(topic) == TOPIC_RELAY) {
    if (message == "ON" || message == "1") {
      relayState = true;
      digitalWrite(RELAY_PIN, HIGH);
      Serial.println("Relay ON");
    } else if (message == "OFF" || message == "0") {
      relayState = false;
      digitalWrite(RELAY_PIN, LOW);
      Serial.println("Relay OFF");
    } else if (message == "TOGGLE") {
      relayState = !relayState;
      digitalWrite(RELAY_PIN, relayState);
    }
    // Publish new state
    mqtt.publish(TOPIC_RELAY_STATE, relayState ? "ON" : "OFF", true);
  }
}

void publishSensorData() {
  // Read sensor
  int rawValue = analogRead(SENSOR_PIN);
  float voltage = (rawValue / 4095.0) * 3.3;
  float temperature = voltage * 100.0; // LM35: 10mV/°C
  float humidity = random(40, 80);     // Replace with real sensor

  // Publish
  char tempStr[8], humStr[8];
  dtostrf(temperature, 4, 1, tempStr);
  dtostrf(humidity, 4, 1, humStr);

  mqtt.publish(TOPIC_TEMP, tempStr);
  mqtt.publish(TOPIC_HUMIDITY, humStr);

  Serial.print("Published: T=");
  Serial.print(tempStr);
  Serial.print("°C, H=");
  Serial.print(humStr);
  Serial.println("%");
}`
  },
  {
    keywords: ['oled', 'ssd1306', 'display', 'screen', 'graphics', 'i2c display'],
    title: 'OLED Display Dashboard',
    description: 'SSD1306 OLED display with animated system dashboard',
    code: `/*
 * ESP32 OLED Display Dashboard
 * Platform: ESP32
 * Generated by EE ZONE AI Code Assistant
 *
 * Drives SSD1306 OLED display (128x64) via I2C.
 * Shows multi-page dashboard with sensor data,
 * bar graphs, and system info.
 */

#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

// ── OLED Configuration ───────────────────────
#define SCREEN_WIDTH  128
#define SCREEN_HEIGHT 64
#define OLED_RESET    -1
#define OLED_ADDR     0x3C

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

// ── Pin Definitions ──────────────────────────
const int SENSOR_PIN = 34;
const int TEMP_PIN   = 35;
const int BUTTON_PIN = 0;   // Boot button for page switching

// ── State ────────────────────────────────────
int currentPage = 0;
const int TOTAL_PAGES = 3;
float tempHistory[64] = {0};
int historyIndex = 0;
unsigned long lastUpdate = 0;

void setup() {
  Serial.begin(115200);
  pinMode(BUTTON_PIN, INPUT_PULLUP);

  if (!display.begin(SSD1306_SWITCHCAPVCC, OLED_ADDR)) {
    Serial.println(F("SSD1306 allocation failed"));
    for (;;);
  }

  // Splash screen
  display.clearDisplay();
  display.setTextSize(2);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(10, 10);
  display.println(F("EE ZONE"));
  display.setTextSize(1);
  display.setCursor(20, 40);
  display.println(F("ESP32 Dashboard"));
  display.display();
  delay(2000);

  Serial.println("OLED Dashboard Ready!");
}

void loop() {
  // Handle button press for page switching
  if (digitalRead(BUTTON_PIN) == LOW) {
    delay(200);  // Debounce
    currentPage = (currentPage + 1) % TOTAL_PAGES;
  }

  if (millis() - lastUpdate >= 500) {
    lastUpdate = millis();

    // Read sensors
    float temp = readTemperature();
    float sensor = readSensor();

    // Store history
    tempHistory[historyIndex] = temp;
    historyIndex = (historyIndex + 1) % 64;

    // Update display
    display.clearDisplay();

    switch (currentPage) {
      case 0: drawMainPage(temp, sensor); break;
      case 1: drawGraphPage(); break;
      case 2: drawSystemPage(); break;
    }

    // Page indicator dots
    for (int i = 0; i < TOTAL_PAGES; i++) {
      if (i == currentPage)
        display.fillCircle(56 + i * 8, 62, 2, SSD1306_WHITE);
      else
        display.drawCircle(56 + i * 8, 62, 2, SSD1306_WHITE);
    }

    display.display();
  }
}

float readTemperature() {
  int raw = analogRead(TEMP_PIN);
  return (raw / 4095.0) * 330.0 - 50.0;
}

float readSensor() {
  int raw = analogRead(SENSOR_PIN);
  return (raw / 4095.0) * 100.0;
}

void drawMainPage(float temp, float sensor) {
  display.setTextSize(1);
  display.setCursor(0, 0);
  display.print(F("Temperature:"));
  display.setTextSize(2);
  display.setCursor(0, 12);
  display.print(temp, 1);
  display.setTextSize(1);
  display.print(F(" C"));

  display.setCursor(0, 35);
  display.print(F("Sensor:"));
  display.setTextSize(2);
  display.setCursor(0, 47);
  display.print(sensor, 0);
  display.setTextSize(1);
  display.print(F(" %"));

  // Bar graph for sensor
  int barWidth = map(constrain((int)sensor, 0, 100), 0, 100, 0, 40);
  display.drawRect(85, 35, 42, 18, SSD1306_WHITE);
  display.fillRect(86, 36, barWidth, 16, SSD1306_WHITE);
}

void drawGraphPage() {
  display.setTextSize(1);
  display.setCursor(0, 0);
  display.print(F("Temp History"));

  // Draw axes
  display.drawLine(10, 12, 10, 55, SSD1306_WHITE);
  display.drawLine(10, 55, 127, 55, SSD1306_WHITE);

  // Draw graph
  for (int i = 1; i < 64; i++) {
    int idx1 = (historyIndex + i - 1) % 64;
    int idx2 = (historyIndex + i) % 64;
    int y1 = map(constrain((int)tempHistory[idx1], -10, 50), -10, 50, 55, 12);
    int y2 = map(constrain((int)tempHistory[idx2], -10, 50), -10, 50, 55, 12);
    int x1 = 11 + (i - 1) * 1.8;
    int x2 = 11 + i * 1.8;
    display.drawLine(x1, y1, x2, y2, SSD1306_WHITE);
  }
}

void drawSystemPage() {
  unsigned long secs = millis() / 1000;
  int hrs = secs / 3600;
  int mins = (secs % 3600) / 60;
  int s = secs % 60;

  display.setTextSize(1);
  display.setCursor(0, 0);
  display.println(F("System Info"));
  display.println();
  display.print(F("Uptime: "));
  display.print(hrs); display.print(F("h "));
  display.print(mins); display.print(F("m "));
  display.print(s); display.println(F("s"));
  display.println();
  display.print(F("Free RAM: "));
  display.print(ESP.getFreeHeap() / 1024);
  display.println(F(" KB"));
  display.print(F("CPU Freq: "));
  display.print(ESP.getCpuFreqMHz());
  display.println(F(" MHz"));
  display.print(F("WiFi: "));
  display.println(WiFi.status() == WL_CONNECTED ? "Connected" : "N/A");
}`
  },
  {
    keywords: ['energy', 'power', 'current', 'voltage', 'watt', 'kwh', 'meter', 'energy monitor'],
    title: 'Energy Monitoring System',
    description: 'WiFi-enabled power/energy meter with web dashboard',
    code: `/*
 * ESP32 Energy Monitoring System
 * Platform: ESP32
 * Generated by EE ZONE AI Code Assistant
 *
 * Monitors voltage, current, and power consumption.
 * Calculates energy (kWh), serves data via WiFi dashboard.
 */

#include <WiFi.h>
#include <WebServer.h>

// ── WiFi ─────────────────────────────────────
const char* ssid     = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";
WebServer server(80);

// ── Pin Definitions ──────────────────────────
const int VOLTAGE_PIN = 34;  // ZMPT101B voltage sensor
const int CURRENT_PIN = 35;  // ACS712 current sensor

// ── Calibration ──────────────────────────────
const float VOLTAGE_SCALE = 234.26;  // Calibration factor
const float CURRENT_SCALE = 30.0;    // ACS712-30A
const float VOLTAGE_OFFSET = 1.65;   // Mid-point voltage (3.3V/2)
const int SAMPLE_COUNT = 1000;       // Samples per reading

// ── Variables ────────────────────────────────
float rmsVoltage = 0;
float rmsCurrent = 0;
float activePower = 0;
float apparentPower = 0;
float powerFactor = 0;
float totalEnergy_kWh = 0;
unsigned long lastEnergyCalc = 0;

void setup() {
  Serial.begin(115200);
  analogReadResolution(12);

  // Connect WiFi
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.print("\\nIP: ");
  Serial.println(WiFi.localIP());

  server.on("/", handleDashboard);
  server.on("/api/data", handleAPI);
  server.begin();

  Serial.println("EE ZONE Energy Monitor Ready!");
}

void loop() {
  server.handleClient();

  static unsigned long lastMeasure = 0;
  if (millis() - lastMeasure >= 1000) {
    lastMeasure = millis();
    measurePower();
    calculateEnergy();
    printReadings();
  }
}

void measurePower() {
  float sumV = 0, sumI = 0, sumP = 0;

  for (int i = 0; i < SAMPLE_COUNT; i++) {
    float rawV = analogRead(VOLTAGE_PIN) * 3.3 / 4095.0 - VOLTAGE_OFFSET;
    float rawI = analogRead(CURRENT_PIN) * 3.3 / 4095.0 - VOLTAGE_OFFSET;

    float instantV = rawV * VOLTAGE_SCALE;
    float instantI = rawI * CURRENT_SCALE;

    sumV += instantV * instantV;
    sumI += instantI * instantI;
    sumP += instantV * instantI;

    delayMicroseconds(200);  // ~50 samples per cycle at 50Hz
  }

  rmsVoltage = sqrt(sumV / SAMPLE_COUNT);
  rmsCurrent = sqrt(sumI / SAMPLE_COUNT);
  activePower = sumP / SAMPLE_COUNT;
  apparentPower = rmsVoltage * rmsCurrent;
  powerFactor = (apparentPower > 0.1) ? activePower / apparentPower : 0;
  powerFactor = constrain(powerFactor, 0, 1);
}

void calculateEnergy() {
  unsigned long now = millis();
  if (lastEnergyCalc > 0) {
    float hours = (now - lastEnergyCalc) / 3600000.0;
    totalEnergy_kWh += (activePower / 1000.0) * hours;
  }
  lastEnergyCalc = now;
}

void printReadings() {
  Serial.print("V: "); Serial.print(rmsVoltage, 1); Serial.print("V  ");
  Serial.print("I: "); Serial.print(rmsCurrent, 2); Serial.print("A  ");
  Serial.print("P: "); Serial.print(activePower, 1); Serial.print("W  ");
  Serial.print("PF: "); Serial.print(powerFactor, 2); Serial.print("  ");
  Serial.print("E: "); Serial.print(totalEnergy_kWh, 4); Serial.println("kWh");
}

void handleAPI() {
  String json = "{"
    "\\"voltage\\":" + String(rmsVoltage, 1) + ","
    "\\"current\\":" + String(rmsCurrent, 2) + ","
    "\\"power\\":" + String(activePower, 1) + ","
    "\\"apparent_power\\":" + String(apparentPower, 1) + ","
    "\\"power_factor\\":" + String(powerFactor, 2) + ","
    "\\"energy_kwh\\":" + String(totalEnergy_kWh, 4) +
  "}";
  server.send(200, "application/json", json);
}

void handleDashboard() {
  String html = R"rawliteral(
<!DOCTYPE html><html><head><title>EE ZONE Energy Monitor</title>
<meta name='viewport' content='width=device-width,initial-scale=1'>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',sans-serif;background:#0a0a1a;color:#fff;padding:20px}
h1{text-align:center;background:linear-gradient(135deg,#9C4AFF,#FF00C8);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:20px;font-size:1.8em}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;max-width:700px;margin:0 auto}
.card{background:rgba(156,74,255,0.08);border:1px solid rgba(156,74,255,0.25);border-radius:12px;padding:16px;text-align:center}
.label{color:#B8A7E0;font-size:0.8em}
.value{font-size:2.2em;font-weight:700;margin:4px 0}
.unit{font-size:0.4em;color:#B8A7E0}
.v{color:#00D4FF} .a{color:#FF00C8} .w{color:#FFB800} .pf{color:#00FF88} .e{color:#FF6B6B} .va{color:#9C4AFF}
</style></head><body>
<h1>⚡ Energy Monitor</h1>
<div class='grid'>
<div class='card'><div class='label'>Voltage</div><div class='value v' id='v'>--<span class='unit'>V</span></div></div>
<div class='card'><div class='label'>Current</div><div class='value a' id='i'>--<span class='unit'>A</span></div></div>
<div class='card'><div class='label'>Active Power</div><div class='value w' id='p'>--<span class='unit'>W</span></div></div>
<div class='card'><div class='label'>Apparent Power</div><div class='value va' id='ap'>--<span class='unit'>VA</span></div></div>
<div class='card'><div class='label'>Power Factor</div><div class='value pf' id='pf'>--</div></div>
<div class='card'><div class='label'>Energy</div><div class='value e' id='e'>--<span class='unit'>kWh</span></div></div>
</div>
<script>
function f(){fetch('/api/data').then(r=>r.json()).then(d=>{
document.getElementById('v').innerHTML=d.voltage.toFixed(1)+'<span class="unit">V</span>';
document.getElementById('i').innerHTML=d.current.toFixed(2)+'<span class="unit">A</span>';
document.getElementById('p').innerHTML=d.power.toFixed(0)+'<span class="unit">W</span>';
document.getElementById('ap').innerHTML=d.apparent_power.toFixed(0)+'<span class="unit">VA</span>';
document.getElementById('pf').textContent=d.power_factor.toFixed(2);
document.getElementById('e').innerHTML=d.energy_kwh.toFixed(3)+'<span class="unit">kWh</span>';
})}setInterval(f,2000);f();
</script></body></html>)rawliteral";
  server.send(200, "text/html", html);
}`
  }
];

// ─── PLC TEMPLATES ──────────────────────────────────────────────────

const plcTemplates: CodeTemplate[] = [
  {
    keywords: ['motor', 'start', 'stop', 'run', 'control', 'starter', 'contactor'],
    title: 'Motor Start/Stop Circuit',
    description: 'Motor control with start/stop, overload, and seal-in',
    code: `(*
 * Motor Start/Stop Control
 * Platform: PLC (IEC 61131-3 Structured Text)
 * Generated by EE ZONE AI Code Assistant
 *
 * Standard motor start/stop circuit with:
 * - Momentary start/stop buttons
 * - Overload protection
 * - Seal-in (latch) logic
 * - Running hours counter
 * - Start count tracker
 *)

PROGRAM MotorControl
VAR
    // ── INPUTS ──────────────────────
    StartButton     : BOOL := FALSE;   // Momentary start (NO)
    StopButton      : BOOL := TRUE;    // Momentary stop (NC) - normally TRUE
    OverloadTrip    : BOOL := FALSE;   // Thermal overload contact (NC)
    EmergencyStop   : BOOL := TRUE;    // E-Stop (NC) - normally TRUE

    // ── OUTPUTS ─────────────────────
    MotorContactor  : BOOL := FALSE;   // Main contactor output
    RunIndicator    : BOOL := FALSE;   // Green pilot light
    FaultIndicator  : BOOL := FALSE;   // Red pilot light
    AlarmBuzzer     : BOOL := FALSE;   // Audible alarm

    // ── INTERNAL ────────────────────
    SealIn          : BOOL := FALSE;   // Latch memory
    FaultLatched    : BOOL := FALSE;   // Fault memory
    StartCounter    : INT  := 0;       // Number of starts
    RunTimer        : TON;             // Running time
    RunningHours    : REAL := 0.0;     // Total running hours
    FaultResetBtn   : BOOL := FALSE;   // Fault reset button
END_VAR

// ── FAULT DETECTION ─────────────────
IF OverloadTrip THEN
    FaultLatched := TRUE;
    SealIn := FALSE;
END_IF;

IF NOT EmergencyStop THEN
    FaultLatched := TRUE;
    SealIn := FALSE;
END_IF;

// ── FAULT RESET ─────────────────────
IF FaultResetBtn AND NOT OverloadTrip AND EmergencyStop THEN
    FaultLatched := FALSE;
END_IF;

// ── MOTOR START/STOP LOGIC ──────────
// Start condition: Start button pressed, Stop not pressed, No faults
IF StartButton AND StopButton AND NOT FaultLatched THEN
    IF NOT SealIn THEN
        StartCounter := StartCounter + 1;  // Count starts
    END_IF;
    SealIn := TRUE;  // Latch on
END_IF;

// Stop condition: Stop button released
IF NOT StopButton THEN
    SealIn := FALSE;
END_IF;

// ── OUTPUT ASSIGNMENTS ──────────────
MotorContactor := SealIn AND NOT FaultLatched;
RunIndicator   := MotorContactor;
FaultIndicator := FaultLatched;
AlarmBuzzer    := FaultLatched AND NOT FaultResetBtn;

// ── RUNNING HOURS ───────────────────
RunTimer(IN := MotorContactor, PT := T#1H);
IF RunTimer.Q THEN
    RunningHours := RunningHours + 1.0;
    RunTimer(IN := FALSE);  // Reset timer
END_IF;

END_PROGRAM`
  },
  {
    keywords: ['traffic', 'light', 'signal', 'sequence', 'timer', 'pedestrian'],
    title: 'Traffic Light Controller',
    description: 'Four-way traffic light sequence with pedestrian crossing',
    code: `(*
 * Traffic Light Sequence Controller
 * Platform: PLC (IEC 61131-3 Structured Text)
 * Generated by EE ZONE AI Code Assistant
 *
 * Controls a 4-way intersection traffic light system
 * with pedestrian crossing request and emergency override.
 *)

PROGRAM TrafficLightController
VAR
    // ── INPUTS ──────────────────────
    PedestrianRequest  : BOOL := FALSE;
    EmergencyOverride  : BOOL := FALSE;
    NightMode          : BOOL := FALSE;
    SystemEnable       : BOOL := TRUE;

    // ── OUTPUTS (North-South) ───────
    NS_Red    : BOOL := TRUE;
    NS_Yellow : BOOL := FALSE;
    NS_Green  : BOOL := FALSE;

    // ── OUTPUTS (East-West) ─────────
    EW_Red    : BOOL := TRUE;
    EW_Yellow : BOOL := FALSE;
    EW_Green  : BOOL := FALSE;

    // ── OUTPUTS (Pedestrian) ────────
    PED_Walk    : BOOL := FALSE;
    PED_DontWalk: BOOL := TRUE;

    // ── INTERNAL ────────────────────
    State         : INT := 0;
    StateTimer    : TON;
    StateDuration : TIME := T#10S;
    FlashTimer    : TON;
    FlashState    : BOOL := FALSE;
    PedRequested  : BOOL := FALSE;
END_VAR

// ── EMERGENCY OVERRIDE ──────────────
IF EmergencyOverride THEN
    NS_Red := TRUE; NS_Yellow := FALSE; NS_Green := FALSE;
    EW_Red := TRUE; EW_Yellow := FALSE; EW_Green := FALSE;
    PED_DontWalk := TRUE; PED_Walk := FALSE;
    RETURN;
END_IF;

// ── NIGHT MODE (FLASHING YELLOW) ────
IF NightMode OR NOT SystemEnable THEN
    FlashTimer(IN := NOT FlashTimer.Q, PT := T#1S);
    IF FlashTimer.Q THEN
        FlashState := NOT FlashState;
    END_IF;
    NS_Red := FALSE; NS_Yellow := FlashState; NS_Green := FALSE;
    EW_Red := FALSE; EW_Yellow := FlashState; EW_Green := FALSE;
    PED_DontWalk := TRUE; PED_Walk := FALSE;
    RETURN;
END_IF;

// ── PEDESTRIAN REQUEST LATCH ────────
IF PedestrianRequest THEN
    PedRequested := TRUE;
END_IF;

// ── MAIN SEQUENCE STATE MACHINE ─────
StateTimer(IN := TRUE, PT := StateDuration);

IF StateTimer.Q THEN
    StateTimer(IN := FALSE);  // Reset timer

    CASE State OF
    0:  // NS Green, EW Red
        State := 1;
        StateDuration := T#3S;  // Yellow duration

    1:  // NS Yellow, EW Red
        IF PedRequested THEN
            State := 4;  // Go to pedestrian phase
            StateDuration := T#8S;
        ELSE
            State := 2;
            StateDuration := T#10S;
        END_IF;

    2:  // NS Red, EW Green
        State := 3;
        StateDuration := T#3S;

    3:  // NS Red, EW Yellow
        State := 0;
        StateDuration := T#10S;

    4:  // Pedestrian Walk phase
        State := 5;
        StateDuration := T#5S;
        PedRequested := FALSE;

    5:  // Pedestrian flashing Don't Walk
        State := 2;
        StateDuration := T#10S;
    END_CASE;

    StateTimer(IN := TRUE);
END_IF;

// ── OUTPUT ASSIGNMENTS BY STATE ─────
CASE State OF
0:  NS_Green := TRUE; NS_Yellow := FALSE; NS_Red := FALSE;
    EW_Green := FALSE; EW_Yellow := FALSE; EW_Red := TRUE;
    PED_Walk := FALSE; PED_DontWalk := TRUE;

1:  NS_Green := FALSE; NS_Yellow := TRUE; NS_Red := FALSE;
    EW_Green := FALSE; EW_Yellow := FALSE; EW_Red := TRUE;
    PED_Walk := FALSE; PED_DontWalk := TRUE;

2:  NS_Green := FALSE; NS_Yellow := FALSE; NS_Red := TRUE;
    EW_Green := TRUE; EW_Yellow := FALSE; EW_Red := FALSE;
    PED_Walk := FALSE; PED_DontWalk := TRUE;

3:  NS_Green := FALSE; NS_Yellow := FALSE; NS_Red := TRUE;
    EW_Green := FALSE; EW_Yellow := TRUE; EW_Red := FALSE;
    PED_Walk := FALSE; PED_DontWalk := TRUE;

4:  NS_Green := FALSE; NS_Yellow := FALSE; NS_Red := TRUE;
    EW_Green := FALSE; EW_Yellow := FALSE; EW_Red := TRUE;
    PED_Walk := TRUE; PED_DontWalk := FALSE;

5:  NS_Green := FALSE; NS_Yellow := FALSE; NS_Red := TRUE;
    EW_Green := FALSE; EW_Yellow := FALSE; EW_Red := TRUE;
    PED_Walk := FALSE; PED_DontWalk := TRUE;
END_CASE;

END_PROGRAM`
  },
  {
    keywords: ['conveyor', 'belt', 'production', 'line', 'manufacturing', 'sensor', 'count'],
    title: 'Conveyor Belt Controller',
    description: 'Industrial conveyor belt control with product counting',
    code: `(*
 * Conveyor Belt Control System
 * Platform: PLC (IEC 61131-3 Structured Text)
 * Generated by EE ZONE AI Code Assistant
 *
 * Controls an industrial conveyor belt with:
 * - Speed control (VFD interface)
 * - Product counting via photoelectric sensor
 * - Jam detection and auto-stop
 * - Batch counting with auto-pause
 *)

PROGRAM ConveyorControl
VAR
    // ── INPUTS ──────────────────────
    StartButton     : BOOL := FALSE;
    StopButton      : BOOL := TRUE;    // NC
    EmergencyStop   : BOOL := TRUE;    // NC
    ProductSensor   : BOOL := FALSE;   // Photoelectric sensor
    JamSensor       : BOOL := FALSE;   // Jam detection
    SpeedPot        : INT  := 500;     // 0-1000 analog input

    // ── OUTPUTS ─────────────────────
    ConveyorRun     : BOOL := FALSE;   // Motor contactor
    SpeedOutput     : INT  := 0;       // 0-1000 analog to VFD
    GreenLight      : BOOL := FALSE;   // Running indicator
    RedLight        : BOOL := FALSE;   // Fault indicator
    YellowLight     : BOOL := FALSE;   // Pause/batch complete

    // ── INTERNAL ────────────────────
    Running         : BOOL := FALSE;
    Faulted         : BOOL := FALSE;
    FaultCode       : INT  := 0;
    ProductCount    : DINT := 0;
    BatchSize       : INT  := 100;     // Products per batch
    BatchCount      : INT  := 0;
    BatchComplete   : BOOL := FALSE;
    PrevSensorState : BOOL := FALSE;
    JamTimer        : TON;
    FaultResetBtn   : BOOL := FALSE;
END_VAR

// ── FAULT DETECTION ─────────────────
IF NOT EmergencyStop THEN
    Faulted := TRUE;
    FaultCode := 1;  // E-Stop
    Running := FALSE;
END_IF;

IF JamSensor THEN
    JamTimer(IN := TRUE, PT := T#3S);
    IF JamTimer.Q THEN
        Faulted := TRUE;
        FaultCode := 2;  // Jam detected
        Running := FALSE;
    END_IF;
ELSE
    JamTimer(IN := FALSE);
END_IF;

// ── FAULT RESET ─────────────────────
IF FaultResetBtn AND EmergencyStop AND NOT JamSensor THEN
    Faulted := FALSE;
    FaultCode := 0;
    BatchComplete := FALSE;
END_IF;

// ── START/STOP LOGIC ────────────────
IF StartButton AND StopButton AND NOT Faulted AND NOT BatchComplete THEN
    Running := TRUE;
END_IF;

IF NOT StopButton THEN
    Running := FALSE;
END_IF;

// ── PRODUCT COUNTING ────────────────
// Detect rising edge of product sensor
IF ProductSensor AND NOT PrevSensorState AND Running THEN
    ProductCount := ProductCount + 1;
    BatchCount := BatchCount + 1;

    // Check batch complete
    IF BatchCount >= BatchSize THEN
        BatchComplete := TRUE;
        Running := FALSE;
        BatchCount := 0;
    END_IF;
END_IF;
PrevSensorState := ProductSensor;

// ── SPEED CONTROL ───────────────────
IF Running THEN
    SpeedOutput := SpeedPot;  // Pass through speed setting
ELSE
    SpeedOutput := 0;
END_IF;

// ── OUTPUT ASSIGNMENTS ──────────────
ConveyorRun := Running;
GreenLight  := Running;
RedLight    := Faulted;
YellowLight := BatchComplete;

END_PROGRAM`
  },
  {
    keywords: ['tank', 'level', 'pump', 'water', 'fill', 'drain', 'float', 'liquid'],
    title: 'Tank Level Controller',
    description: 'Water tank level control with pump and valve automation',
    code: `(*
 * Tank Level Control System
 * Platform: PLC (IEC 61131-3 Structured Text)
 * Generated by EE ZONE AI Code Assistant
 *
 * Automated tank level control with:
 * - Analog level sensor (4-20mA)
 * - Fill pump and drain valve control
 * - High/low level alarms
 * - Overflow protection
 * - Auto/Manual modes
 *)

PROGRAM TankLevelControl
VAR
    // ── INPUTS ──────────────────────
    LevelSensor     : INT  := 0;       // 4-20mA → 0-1000 (0-100%)
    HighLevelSwitch : BOOL := FALSE;   // Float switch - high
    LowLevelSwitch  : BOOL := FALSE;   // Float switch - low
    AutoMode        : BOOL := TRUE;    // Auto/Manual selector
    ManualFillBtn   : BOOL := FALSE;
    ManualDrainBtn  : BOOL := FALSE;
    EStop           : BOOL := TRUE;    // NC

    // ── OUTPUTS ─────────────────────
    FillPump        : BOOL := FALSE;   // Fill pump contactor
    DrainValve      : BOOL := FALSE;   // Drain solenoid valve
    HighAlarm       : BOOL := FALSE;   // High level alarm
    LowAlarm        : BOOL := FALSE;   // Low level alarm
    OverflowAlarm   : BOOL := FALSE;   // Overflow alarm

    // ── CONFIGURATION ───────────────
    SetpointHigh    : REAL := 80.0;    // % - Stop filling
    SetpointLow     : REAL := 20.0;    // % - Start filling
    AlarmHigh       : REAL := 90.0;    // % - High alarm
    AlarmLow        : REAL := 10.0;    // % - Low alarm

    // ── INTERNAL ────────────────────
    LevelPercent    : REAL := 0.0;
    Filling         : BOOL := FALSE;
    Draining        : BOOL := FALSE;
END_VAR

// ── SAFETY CHECK ────────────────────
IF NOT EStop THEN
    FillPump := FALSE;
    DrainValve := FALSE;
    OverflowAlarm := TRUE;
    RETURN;
END_IF;

// ── CALCULATE LEVEL ─────────────────
LevelPercent := INT_TO_REAL(LevelSensor) / 10.0;  // 0-1000 → 0-100%
LevelPercent := MAX(0.0, MIN(100.0, LevelPercent));

// ── OVERFLOW PROTECTION ─────────────
IF HighLevelSwitch OR LevelPercent >= 95.0 THEN
    FillPump := FALSE;
    Filling := FALSE;
    OverflowAlarm := TRUE;
END_IF;

// ── AUTO MODE ───────────────────────
IF AutoMode AND NOT OverflowAlarm THEN
    // Hysteresis fill control
    IF LevelPercent <= SetpointLow THEN
        Filling := TRUE;
    ELSIF LevelPercent >= SetpointHigh THEN
        Filling := FALSE;
    END_IF;

    FillPump := Filling;
    DrainValve := FALSE;

// ── MANUAL MODE ─────────────────────
ELSE
    IF NOT AutoMode THEN
        FillPump := ManualFillBtn AND NOT OverflowAlarm;
        DrainValve := ManualDrainBtn AND NOT LowLevelSwitch;
    END_IF;
END_IF;

// ── ALARMS ──────────────────────────
HighAlarm := LevelPercent >= AlarmHigh;
LowAlarm  := LevelPercent <= AlarmLow;

// Reset overflow alarm when level drops
IF LevelPercent < 85.0 AND NOT HighLevelSwitch THEN
    OverflowAlarm := FALSE;
END_IF;

END_PROGRAM`
  }
];

// ─── SMART MATCHING ENGINE ──────────────────────────────────────────

function scoreTemplate(template: CodeTemplate, prompt: string): number {
  const lowerPrompt = prompt.toLowerCase();
  let score = 0;
  
  for (const keyword of template.keywords) {
    if (lowerPrompt.includes(keyword.toLowerCase())) {
      // Exact word match scores higher
      const regex = new RegExp('\\b' + keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b', 'i');
      if (regex.test(prompt)) {
        score += 10;
      } else {
        score += 5;
      }
    }
  }
  
  // Bonus for title match
  if (lowerPrompt.includes(template.title.toLowerCase())) {
    score += 20;
  }
  
  return score;
}

function findBestTemplate(templates: CodeTemplate[], prompt: string): CodeTemplate | null {
  let bestTemplate: CodeTemplate | null = null;
  let bestScore = 0;
  
  for (const template of templates) {
    const score = scoreTemplate(template, prompt);
    if (score > bestScore) {
      bestScore = score;
      bestTemplate = template;
    }
  }
  
  return bestScore >= 5 ? bestTemplate : null;
}

// ─── DEFAULT TEMPLATES (when no match found) ────────────────────────

function getDefaultTemplate(platform: string, prompt: string): string {
  switch (platform.toLowerCase()) {
    case 'arduino':
      return `/*
 * Custom Arduino Project
 * Platform: Arduino
 * Generated by EE ZONE AI Code Assistant
 *
 * Requirement: ${prompt}
 *
 * This is a starter template. The code below provides
 * a complete framework for your project.
 */

// ── Pin Definitions ──────────────────────────
// Adjust these pins based on your circuit
const int OUTPUT_PIN_1 = 13;   // Digital output
const int OUTPUT_PIN_2 = 12;   // Digital output
const int INPUT_PIN_1  = 2;    // Digital input
const int ANALOG_PIN   = A0;   // Analog input
const int PWM_PIN      = 9;    // PWM output

// ── Configuration ────────────────────────────
const unsigned long UPDATE_INTERVAL = 1000; // ms
unsigned long lastUpdate = 0;
int sensorValue = 0;

void setup() {
  Serial.begin(9600);
  
  // Configure pins
  pinMode(OUTPUT_PIN_1, OUTPUT);
  pinMode(OUTPUT_PIN_2, OUTPUT);
  pinMode(INPUT_PIN_1, INPUT_PULLUP);
  
  // Initialize outputs
  digitalWrite(OUTPUT_PIN_1, LOW);
  digitalWrite(OUTPUT_PIN_2, LOW);
  
  Serial.println(F("╔══════════════════════════════════════╗"));
  Serial.println(F("║   EE ZONE Custom Project            ║"));
  Serial.println(F("╚══════════════════════════════════════╝"));
  Serial.println(F("System initialized and ready."));
}

void loop() {
  unsigned long now = millis();
  
  // Read inputs
  bool buttonState = (digitalRead(INPUT_PIN_1) == LOW);
  sensorValue = analogRead(ANALOG_PIN);
  
  // Process at regular intervals
  if (now - lastUpdate >= UPDATE_INTERVAL) {
    lastUpdate = now;
    
    // Map sensor to PWM output
    int pwmValue = map(sensorValue, 0, 1023, 0, 255);
    analogWrite(PWM_PIN, pwmValue);
    
    // Toggle output based on sensor threshold
    if (sensorValue > 512) {
      digitalWrite(OUTPUT_PIN_1, HIGH);
    } else {
      digitalWrite(OUTPUT_PIN_1, LOW);
    }
    
    // Serial monitoring
    Serial.print(F("Sensor: "));
    Serial.print(sensorValue);
    Serial.print(F("  PWM: "));
    Serial.print(pwmValue);
    Serial.print(F("  Button: "));
    Serial.println(buttonState ? "PRESSED" : "RELEASED");
  }
  
  // Button toggle for output 2
  if (buttonState) {
    digitalWrite(OUTPUT_PIN_2, !digitalRead(OUTPUT_PIN_2));
    delay(200); // Simple debounce
  }
}`;
    
    case 'esp32':
      return `/*
 * Custom ESP32 IoT Project
 * Platform: ESP32
 * Generated by EE ZONE AI Code Assistant
 *
 * Requirement: ${prompt}
 *
 * WiFi-connected project with web interface.
 */

#include <WiFi.h>
#include <WebServer.h>

const char* ssid     = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";

WebServer server(80);

const int OUTPUT_PIN = 2;
const int SENSOR_PIN = 34;
float sensorValue = 0;
bool outputState = false;

void setup() {
  Serial.begin(115200);
  pinMode(OUTPUT_PIN, OUTPUT);
  
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.print("\\nIP: ");
  Serial.println(WiFi.localIP());
  
  server.on("/", []() {
    String html = "<html><body style='background:#0a0a1a;color:white;font-family:sans-serif;text-align:center;padding:40px'>";
    html += "<h1 style='color:#9C4AFF'>EE ZONE ESP32</h1>";
    html += "<p>Sensor: " + String(sensorValue, 1) + "</p>";
    html += "<p>Output: " + String(outputState ? "ON" : "OFF") + "</p>";
    html += "<a href='/toggle' style='color:#FF00C8'>Toggle Output</a>";
    html += "</body></html>";
    server.send(200, "text/html", html);
  });
  
  server.on("/toggle", []() {
    outputState = !outputState;
    digitalWrite(OUTPUT_PIN, outputState);
    server.sendHeader("Location", "/");
    server.send(303);
  });
  
  server.begin();
  Serial.println("EE ZONE ESP32 Ready!");
}

void loop() {
  server.handleClient();
  sensorValue = analogRead(SENSOR_PIN) * 3.3 / 4095.0;
}`;
    
    case 'plc':
    default:
      return `(*
 * Custom PLC Program
 * Platform: PLC (IEC 61131-3 Structured Text)
 * Generated by EE ZONE AI Code Assistant
 *
 * Requirement: ${prompt}
 *)

PROGRAM CustomControl
VAR
    // ── INPUTS ──────────────────────
    Input1      : BOOL := FALSE;
    Input2      : BOOL := FALSE;
    AnalogIn    : INT  := 0;       // 0-1000 scaled
    
    // ── OUTPUTS ─────────────────────
    Output1     : BOOL := FALSE;
    Output2     : BOOL := FALSE;
    AnalogOut   : INT  := 0;       // 0-1000 scaled
    
    // ── INTERNAL ────────────────────
    Running     : BOOL := FALSE;
    Timer1      : TON;
    Counter1    : CTU;
END_VAR

// ── MAIN LOGIC ──────────────────────
IF Input1 AND NOT Input2 THEN
    Running := TRUE;
END_IF;

IF Input2 THEN
    Running := FALSE;
END_IF;

// Timer example: 5 second delay
Timer1(IN := Running, PT := T#5S);

// Counter example
Counter1(CU := Input1, RESET := Input2, PV := 10);

// Output assignments
Output1 := Running;
Output2 := Timer1.Q;
AnalogOut := AnalogIn;  // Pass-through

END_PROGRAM`;
  }
}

// ─── PUBLIC API ─────────────────────────────────────────────────────

export function generateCode(platform: string, prompt: string): { code: string; title: string; description: string } {
  let templates: CodeTemplate[];
  
  switch (platform.toLowerCase()) {
    case 'arduino':
      templates = arduinoTemplates;
      break;
    case 'esp32':
      templates = esp32Templates;
      break;
    case 'plc':
      templates = plcTemplates;
      break;
    default:
      templates = arduinoTemplates;
  }
  
  const bestMatch = findBestTemplate(templates, prompt);
  
  if (bestMatch) {
    return {
      code: bestMatch.code,
      title: bestMatch.title,
      description: bestMatch.description,
    };
  }
  
  return {
    code: getDefaultTemplate(platform, prompt),
    title: 'Custom ' + platform.toUpperCase() + ' Project',
    description: 'Generated code based on your requirements',
  };
}
