import { NextRequest, NextResponse } from 'next/server';
import { generateCode } from '@/lib/code-generator';

export async function POST(req: NextRequest) {
  try {
    const { platform, prompt, useOnlineAI, apiKey } = await req.json();

    if (!prompt) {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 });
    }

    if (useOnlineAI) {
      const finalApiKey = apiKey || process.env.OPENROUTER_API_KEY;
      if (!finalApiKey) {
        return NextResponse.json({ error: 'OpenRouter API key is required. Please provide it in the UI.' }, { status: 400 });
      }

      const systemPrompt = `You are an expert embedded systems and industrial automation code generator. Generate complete, production-ready code based on user requirements.

PLATFORMS:
- PLC: Generate IEC 61131-3 Structured Text or Ladder Logic (text representation)
- Arduino: Generate Arduino C++ code with proper setup() and loop()
- ESP32: Generate ESP32 Arduino code with WiFi, BLE, and ESP-IDF features

REQUIREMENTS:
1. Generate COMPLETE, COMPILABLE code.
2. Include all necessary #includes and library imports.
3. Respond ONLY with the code block.`;

      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${finalApiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://eezone.com',
          'X-Title': 'EE Zone Code Assistant',
        },
        body: JSON.stringify({
          model: 'google/gemma-3-27b-it:free',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: `Platform: ${(platform || 'arduino').toUpperCase()}\n\nRequirement: ${prompt}` }
          ],
          temperature: 0.3,
          max_tokens: 3000,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        return NextResponse.json(
          { error: 'Online AI Error (API Key Expired or Rate Limited)', details: errorData },
          { status: response.status }
        );
      }

      const data = await response.json();
      const code = data.choices?.[0]?.message?.content || '';

      return NextResponse.json({
        code,
        title: `Generated by Online AI`,
        description: 'Online AI Generation',
        model: data.model,
        source: 'online',
      });
    }

    // Use local code generation engine (always works, no API key needed)
    const result = generateCode(platform || 'arduino', prompt);

    return NextResponse.json({
      code: result.code,
      title: result.title,
      description: result.description,
      model: 'eezone-code-engine-v1',
      source: 'local',
    });
  } catch (error) {
    return NextResponse.json(
      { error: 'Internal server error', details: error instanceof Error ? error.message : 'Unknown' },
      { status: 500 }
    );
  }
}
