import { db } from '@/db';
import { downloadableResources } from '@/db/schema';

async function main() {
    const sampleResources = [
        {
            title: 'NEC Wire Ampacity Chart',
            description: 'Comprehensive ampacity tables from the National Electrical Code (NEC) Article 310. Includes current-carrying capacity ratings for copper and aluminum conductors in various installation conditions. Essential reference for wire sizing and electrical system design. Covers temperature ratings of 60°C, 75°C, and 90°C insulation types.',
            fileType: 'PDF',
            fileSize: '2.4 MB',
            fileUrl: '/downloads/nec-ampacity-chart.pdf',
            downloads: 1156,
            category: 'Reference',
            tags: 'ampacity,NEC,wire sizing,current,conductor',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Electrical Symbols Library',
            description: 'Complete collection of standardized electrical symbols for schematic diagrams and blueprints. Includes symbols for switches, outlets, motors, transformers, control devices, and power distribution equipment. Compliant with IEEE and IEC standards. Perfect for creating professional electrical drawings and documentation.',
            fileType: 'PDF',
            fileSize: '1.8 MB',
            fileUrl: '/downloads/electrical-symbols-library.pdf',
            downloads: 892,
            category: 'Reference',
            tags: 'symbols,schematic,diagram,IEEE,IEC,drawing',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'Conduit Fill Calculator Spreadsheet',
            description: 'Excel-based calculator for determining maximum conduit fill according to NEC Chapter 9 Table 4. Automatically calculates allowable conductor quantities based on conduit size, conductor size, and insulation type. Includes formulas for both metallic and non-metallic conduit systems. Supports multiple conductor configurations.',
            fileType: 'XLSX',
            fileSize: '512 KB',
            fileUrl: '/downloads/conduit-fill-calculator.xlsx',
            downloads: 734,
            category: 'Calculations',
            tags: 'conduit,fill,NEC,calculator,raceway,conductor',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            title: 'Motor Full Load Current Table',
            description: 'Reference tables for full-load currents of AC and DC motors at various voltages and horsepower ratings. Includes single-phase, three-phase, and polyphase motor data. Essential for motor circuit design, overload protection sizing, and conductor selection. Based on NEC Article 430 tables.',
            fileType: 'PDF',
            fileSize: '1.2 MB',
            fileUrl: '/downloads/motor-full-load-current.pdf',
            downloads: 654,
            category: 'Reference',
            tags: 'motor,FLC,current,horsepower,NEC,protection',
            createdAt: new Date('2024-03-22').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },
        {
            title: 'Electrical Load Calculation Template',
            description: 'Professional spreadsheet template for residential and commercial electrical load calculations. Automates standard method and optional method calculations per NEC Article 220. Includes sections for general lighting, appliances, HVAC, and special loads. Generates demand factors and service sizing recommendations.',
            fileType: 'XLSX',
            fileSize: '856 KB',
            fileUrl: '/downloads/load-calculation-template.xlsx',
            downloads: 1087,
            category: 'Templates',
            tags: 'load calculation,service,demand,NEC,residential,commercial',
            createdAt: new Date('2024-04-18').toISOString(),
            updatedAt: new Date('2024-04-18').toISOString(),
        },
        {
            title: 'Circuit Breaker Sizing Guide',
            description: 'Detailed guide for proper circuit breaker selection and sizing. Covers standard and special-purpose circuit protection requirements including motor circuits, continuous loads, and HVAC equipment. Includes short-circuit current considerations and selective coordination principles. Features decision trees and sizing examples.',
            fileType: 'PDF',
            fileSize: '3.1 MB',
            fileUrl: '/downloads/breaker-sizing-guide.pdf',
            downloads: 923,
            category: 'Design',
            tags: 'circuit breaker,protection,sizing,OCPD,fault,coordination',
            createdAt: new Date('2024-05-12').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        },
        {
            title: 'Voltage Drop Calculation Worksheet',
            description: 'Interactive Excel worksheet for calculating voltage drop in electrical distribution systems. Supports both AC and DC circuits with various conductor materials and installation methods. Includes formulas for single-phase and three-phase systems. Helps ensure compliance with NEC voltage drop recommendations of 3% for branch circuits and 5% total.',
            fileType: 'XLSX',
            fileSize: '624 KB',
            fileUrl: '/downloads/voltage-drop-calculator.xlsx',
            downloads: 845,
            category: 'Calculations',
            tags: 'voltage drop,calculation,NEC,conductor,distance,efficiency',
            createdAt: new Date('2024-06-08').toISOString(),
            updatedAt: new Date('2024-06-08').toISOString(),
        },
        {
            title: 'Single Line Diagram Template',
            description: 'Professional Microsoft Word template for creating electrical single-line diagrams. Pre-formatted with standard symbols, line weights, and annotation styles. Includes sections for service entrance, main distribution, panels, and load schedules. Suitable for permit applications and construction documentation.',
            fileType: 'DOCX',
            fileSize: '2.8 MB',
            fileUrl: '/downloads/single-line-diagram-template.docx',
            downloads: 567,
            category: 'Templates',
            tags: 'single line,diagram,SLD,drawing,distribution,documentation',
            createdAt: new Date('2024-07-03').toISOString(),
            updatedAt: new Date('2024-07-03').toISOString(),
        },
        {
            title: 'Arc Flash Hazard Assessment Form',
            description: 'Comprehensive template for conducting arc flash hazard assessments per NFPA 70E standards. Includes fields for incident energy calculations, arc flash boundary determination, and PPE category assignment. Features equipment data collection checklist and worker training documentation sections.',
            fileType: 'PDF',
            fileSize: '1.5 MB',
            fileUrl: '/downloads/arc-flash-assessment-form.pdf',
            downloads: 421,
            category: 'Templates',
            tags: 'arc flash,NFPA 70E,safety,PPE,hazard,assessment',
            createdAt: new Date('2024-07-28').toISOString(),
            updatedAt: new Date('2024-07-28').toISOString(),
        },
        {
            title: 'Transformer Nameplate Data Sheet',
            description: 'Excel template for recording and organizing transformer nameplate information. Captures critical data including kVA rating, voltage ratios, impedance, connection diagrams, and cooling class. Useful for maintenance records, load analysis, and short-circuit calculations. Supports both distribution and power transformers.',
            fileType: 'XLSX',
            fileSize: '445 KB',
            fileUrl: '/downloads/transformer-nameplate-data.xlsx',
            downloads: 389,
            category: 'Templates',
            tags: 'transformer,nameplate,data,kVA,impedance,maintenance',
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
    ];

    await db.insert(downloadableResources).values(sampleResources);
    
    console.log('✅ Downloadable resources seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});