import { db } from '@/db';
import { questions } from '@/db/schema';

async function main() {
    const sampleQuestions = [
        // Topic 1: DC Machines (easy, medium, hard)
        {
            topicId: 1,
            difficulty: 'easy',
            questionText: 'What is the primary function of a commutator in a DC motor?',
            optionA: 'To increase voltage output',
            optionB: 'To convert AC to DC internally',
            optionC: 'To reverse the direction of current in the armature windings',
            optionD: 'To cool the motor windings',
            correctOption: 'C',
            explanation: 'The commutator is a mechanical rectifier that reverses the direction of current flow in the armature windings at the appropriate time, ensuring continuous rotation in the same direction. This switching action is essential for converting the electrical input into mechanical rotation.',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            topicId: 1,
            difficulty: 'medium',
            questionText: 'A DC shunt motor has an armature resistance of 0.5Ω and a field resistance of 200Ω. If the supply voltage is 220V and the motor draws 50A, what is the back EMF?',
            optionA: '195V',
            optionB: '205V',
            optionC: '215V',
            optionD: '220V',
            correctOption: 'A',
            explanation: 'Back EMF (Eb) = V - Ia×Ra. First, calculate armature current: Ia = 50A - (220V/200Ω) = 48.9A. Then, Eb = 220V - (48.9A × 0.5Ω) = 195.55V ≈ 195V. The back EMF opposes the applied voltage and is crucial for motor speed regulation.',
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            topicId: 1,
            difficulty: 'hard',
            questionText: 'In a separately excited DC generator, if the field flux is reduced to 80% of its original value while keeping the speed constant, what happens to the generated EMF?',
            optionA: 'Increases by 25%',
            optionB: 'Decreases to 80% of original value',
            optionC: 'Remains constant',
            optionD: 'Decreases to 64% of original value',
            correctOption: 'B',
            explanation: 'According to the EMF equation E = (PΦNz)/(60A), the generated EMF is directly proportional to the flux (Φ). If flux reduces to 80%, the EMF will also reduce to 80% of its original value, assuming speed and other parameters remain constant. This linear relationship is fundamental to DC machine operation.',
            createdAt: new Date('2024-01-12').toISOString(),
        },

        // Topic 2: AC Machines (easy, medium, hard)
        {
            topicId: 2,
            difficulty: 'easy',
            questionText: 'What is the synchronous speed of a 4-pole, 50Hz induction motor?',
            optionA: '1500 RPM',
            optionB: '1800 RPM',
            optionC: '3000 RPM',
            optionD: '750 RPM',
            correctOption: 'A',
            explanation: 'Synchronous speed Ns = (120×f)/P = (120×50)/4 = 1500 RPM. This is the speed at which the rotating magnetic field revolves in the air gap. The actual rotor speed will be slightly less due to slip, which is necessary for torque production in induction motors.',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            topicId: 2,
            difficulty: 'medium',
            questionText: 'A 3-phase induction motor has a synchronous speed of 1500 RPM and operates at 1440 RPM. What is the slip?',
            optionA: '2%',
            optionB: '4%',
            optionC: '6%',
            optionD: '8%',
            correctOption: 'B',
            explanation: 'Slip s = [(Ns - Nr)/Ns] × 100 = [(1500 - 1440)/1500] × 100 = 4%. Slip is essential for induction motor operation as it creates the relative motion between the rotor and stator magnetic fields, which induces currents in the rotor and produces torque.',
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            topicId: 2,
            difficulty: 'hard',
            questionText: 'In a synchronous motor operating at no-load with normal excitation, what happens to the power factor when the field excitation is increased?',
            optionA: 'Power factor becomes leading',
            optionB: 'Power factor becomes lagging',
            optionC: 'Power factor remains unity',
            optionD: 'Power factor becomes zero',
            correctOption: 'A',
            explanation: 'When field excitation is increased beyond normal (over-excitation), the synchronous motor draws leading current and acts as a capacitor, improving the power factor of the system. This phenomenon makes synchronous motors valuable for power factor correction in industrial installations. Under-excitation causes lagging power factor.',
            createdAt: new Date('2024-01-15').toISOString(),
        },

        // Topic 3: Transformers (easy, medium, medium)
        {
            topicId: 3,
            difficulty: 'easy',
            questionText: 'A transformer has 500 primary turns and 100 secondary turns. If the primary voltage is 240V, what is the secondary voltage?',
            optionA: '24V',
            optionB: '48V',
            optionC: '120V',
            optionD: '1200V',
            correctOption: 'B',
            explanation: 'Using the transformer equation V2/V1 = N2/N1, we get V2 = (100/500) × 240V = 48V. This is a step-down transformer with a turns ratio of 5:1. The voltage transformation is directly proportional to the turns ratio, which is a fundamental principle of electromagnetic induction.',
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            topicId: 3,
            difficulty: 'medium',
            questionText: 'What is the primary purpose of a transformer\'s iron core?',
            optionA: 'To provide mechanical support',
            optionB: 'To provide a low reluctance path for magnetic flux',
            optionC: 'To increase the resistance of windings',
            optionD: 'To cool the transformer',
            correctOption: 'B',
            explanation: 'The iron core provides a low reluctance path for magnetic flux, ensuring efficient flux linkage between primary and secondary windings. Laminated silicon steel is typically used to minimize eddy current losses while maintaining high permeability, which is crucial for efficient energy transfer with minimal losses.',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            topicId: 3,
            difficulty: 'medium',
            questionText: 'In a transformer, which type of loss occurs due to alternating magnetic flux in the core?',
            optionA: 'Copper loss only',
            optionB: 'Hysteresis and eddy current losses',
            optionC: 'Mechanical losses',
            optionD: 'Dielectric losses',
            correctOption: 'B',
            explanation: 'Core losses consist of hysteresis losses (due to magnetic domain realignment) and eddy current losses (due to induced currents in the core). These are constant losses that occur whenever the transformer is energized, regardless of load. Laminating the core and using high-grade silicon steel helps minimize these losses.',
            createdAt: new Date('2024-01-18').toISOString(),
        },

        // Topic 4: Power Systems (medium, medium, hard)
        {
            topicId: 4,
            difficulty: 'medium',
            questionText: 'What is the primary advantage of HVDC transmission over HVAC transmission?',
            optionA: 'Lower initial cost',
            optionB: 'Easier voltage transformation',
            optionC: 'Lower transmission losses over long distances',
            optionD: 'Simpler protection systems',
            correctOption: 'C',
            explanation: 'HVDC transmission has lower losses over long distances because there is no reactive power flow, no skin effect, and no charging current. While HVAC is more economical for shorter distances, HVDC becomes advantageous for distances exceeding 600-800 km. Additionally, HVDC allows interconnection of asynchronous AC systems.',
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            topicId: 4,
            difficulty: 'medium',
            questionText: 'In a power system, what does the term "load factor" represent?',
            optionA: 'Peak load divided by average load',
            optionB: 'Average load divided by maximum demand',
            optionC: 'Maximum demand divided by connected load',
            optionD: 'Connected load divided by rated capacity',
            correctOption: 'B',
            explanation: 'Load factor = (Average load)/(Maximum demand) over a specified period. A high load factor indicates efficient utilization of the power system equipment and is economically desirable. It typically varies between 0.5 to 0.8 for most power systems, with industrial loads generally having higher load factors than residential loads.',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            topicId: 4,
            difficulty: 'hard',
            questionText: 'What is the Ferranti effect in power transmission?',
            optionA: 'Voltage drop at the receiving end',
            optionB: 'Voltage rise at the receiving end under light or no-load conditions',
            optionC: 'Power loss due to corona discharge',
            optionD: 'Frequency variation during transmission',
            correctOption: 'B',
            explanation: 'The Ferranti effect causes the receiving end voltage to be higher than the sending end voltage in long, lightly loaded transmission lines due to the capacitive charging current. This occurs because the line capacitance generates reactive power that cannot be absorbed by the load. The effect becomes more pronounced with longer lines and higher voltages, requiring compensation techniques.',
            createdAt: new Date('2024-01-21').toISOString(),
        },

        // Topic 5: Circuit Analysis (easy, easy, medium)
        {
            topicId: 5,
            difficulty: 'easy',
            questionText: 'According to Kirchhoff\'s Current Law (KCL), what is the sum of currents at any node in a circuit?',
            optionA: 'Equal to the supply voltage',
            optionB: 'Equal to zero',
            optionC: 'Equal to the total resistance',
            optionD: 'Equal to the power consumed',
            correctOption: 'B',
            explanation: 'KCL states that the algebraic sum of all currents entering and leaving a node equals zero. This is based on the principle of conservation of charge - charge cannot accumulate at a node. Currents entering the node are considered positive, while currents leaving are negative, and their sum must equal zero.',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            topicId: 5,
            difficulty: 'easy',
            questionText: 'Three resistors of 10Ω, 20Ω, and 30Ω are connected in series. What is the equivalent resistance?',
            optionA: '5Ω',
            optionB: '20Ω',
            optionC: '60Ω',
            optionD: '100Ω',
            correctOption: 'C',
            explanation: 'For series connection, the equivalent resistance is the sum of individual resistances: Req = R1 + R2 + R3 = 10Ω + 20Ω + 30Ω = 60Ω. In series circuits, the current through all resistors is the same, but voltage divides proportionally to the resistance values.',
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            topicId: 5,
            difficulty: 'medium',
            questionText: 'What is the Thevenin equivalent voltage for a circuit when the open-circuit voltage between terminals A and B is 12V?',
            optionA: '6V',
            optionB: '12V',
            optionC: '24V',
            optionD: 'Cannot be determined without load',
            correctOption: 'B',
            explanation: 'The Thevenin equivalent voltage (Vth) is equal to the open-circuit voltage across the terminals. In this case, Vth = 12V. Thevenin\'s theorem simplifies complex circuits by replacing them with a single voltage source and series resistance, making analysis of different loads much easier.',
            createdAt: new Date('2024-01-24').toISOString(),
        },

        // Topic 6: Op-Amps (easy, medium, hard)
        {
            topicId: 6,
            difficulty: 'easy',
            questionText: 'What are the two golden rules for an ideal operational amplifier?',
            optionA: 'Infinite input impedance and zero output impedance',
            optionB: 'No current flows into inputs and voltage at inputs is equal',
            optionC: 'Infinite gain and zero offset voltage',
            optionD: 'High CMRR and low drift',
            correctOption: 'B',
            explanation: 'The two golden rules are: (1) No current flows into either input terminal (infinite input impedance), and (2) The voltage at both input terminals is equal when negative feedback is applied. These assumptions greatly simplify op-amp circuit analysis and are valid for most practical applications with ideal op-amps.',
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            topicId: 6,
            difficulty: 'medium',
            questionText: 'An inverting amplifier has Rf = 100kΩ and Rin = 10kΩ. What is the voltage gain?',
            optionA: '-10',
            optionB: '+10',
            optionC: '-0.1',
            optionD: '+0.1',
            correctOption: 'A',
            explanation: 'For an inverting amplifier, voltage gain Av = -Rf/Rin = -100kΩ/10kΩ = -10. The negative sign indicates 180° phase inversion between input and output signals. This configuration provides predictable gain determined solely by the external resistor ratio, independent of the op-amp\'s open-loop gain.',
            createdAt: new Date('2024-01-26').toISOString(),
        },
        {
            topicId: 6,
            difficulty: 'hard',
            questionText: 'What is the primary cause of slew rate limitation in operational amplifiers?',
            optionA: 'Low power supply voltage',
            optionB: 'Internal current source limitation in charging compensation capacitor',
            optionC: 'High input impedance',
            optionD: 'Thermal noise in transistors',
            correctOption: 'B',
            explanation: 'Slew rate is limited by the maximum current available to charge and discharge the internal compensation capacitor. The slew rate (dV/dt) = Imax/C, where Imax is the maximum current and C is the compensation capacitance. This limitation affects the maximum frequency of large signals that can be accurately reproduced without distortion.',
            createdAt: new Date('2024-01-27').toISOString(),
        },

        // Topic 7: Digital Electronics (easy, medium, medium)
        {
            topicId: 7,
            difficulty: 'easy',
            questionText: 'How many input combinations are possible for a 3-input logic gate?',
            optionA: '3',
            optionB: '6',
            optionC: '8',
            optionD: '9',
            correctOption: 'C',
            explanation: 'For n inputs, the number of possible combinations is 2^n. For 3 inputs, this gives 2^3 = 8 combinations (000, 001, 010, 011, 100, 101, 110, 111). Each input can be either 0 or 1, and all combinations must be considered when creating truth tables for logic gate analysis.',
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            topicId: 7,
            difficulty: 'medium',
            questionText: 'What is the Boolean expression for the output of an XOR gate with inputs A and B?',
            optionA: 'A + B',
            optionB: 'A · B',
            optionC: 'A ⊕ B = A\'B + AB\'',
            optionD: 'A + B\'',
            correctOption: 'C',
            explanation: 'The XOR (exclusive OR) gate output is high only when inputs are different. Its Boolean expression is A ⊕ B = A\'B + AB\', meaning (NOT A AND B) OR (A AND NOT B). XOR gates are fundamental in arithmetic circuits, parity checkers, and error detection systems.',
            createdAt: new Date('2024-01-29').toISOString(),
        },
        {
            topicId: 7,
            difficulty: 'medium',
            questionText: 'In a J-K flip-flop, what happens when both J and K inputs are HIGH?',
            optionA: 'Output remains unchanged',
            optionB: 'Output is set to HIGH',
            optionC: 'Output is reset to LOW',
            optionD: 'Output toggles to opposite state',
            correctOption: 'D',
            explanation: 'When J=1 and K=1, the J-K flip-flop toggles its output to the opposite state on each clock pulse. This toggle mode eliminates the indeterminate state problem of S-R flip-flops and makes J-K flip-flops versatile for counters, frequency dividers, and state machines.',
            createdAt: new Date('2024-01-30').toISOString(),
        },

        // Topic 8: Power Electronics (medium, medium, hard)
        {
            topicId: 8,
            difficulty: 'medium',
            questionText: 'What is the average output voltage of a single-phase half-wave rectifier with a peak input voltage of 100V?',
            optionA: '31.8V',
            optionB: '45V',
            optionC: '63.6V',
            optionD: '70.7V',
            correctOption: 'A',
            explanation: 'For a half-wave rectifier, average output voltage Vdc = Vm/π = 100V/π ≈ 31.8V, where Vm is the peak voltage. The rectifier conducts only during positive half-cycles, resulting in a pulsating DC output. The actual output will be slightly less due to diode voltage drop.',
            createdAt: new Date('2024-01-31').toISOString(),
        },
        {
            topicId: 8,
            difficulty: 'medium',
            questionText: 'In a buck converter, what is the relationship between output voltage (Vo) and input voltage (Vin)?',
            optionA: 'Vo > Vin always',
            optionB: 'Vo < Vin always',
            optionC: 'Vo = Vin',
            optionD: 'Vo can be greater or less than Vin',
            correctOption: 'B',
            explanation: 'A buck converter is a step-down DC-DC converter where the output voltage is always less than the input voltage. The relationship is Vo = D × Vin, where D is the duty cycle (0 < D < 1). Buck converters are widely used in voltage regulators for portable electronics and computing devices.',
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            topicId: 8,
            difficulty: 'hard',
            questionText: 'What is the main advantage of using an IGBT over a MOSFET in high-power applications?',
            optionA: 'Faster switching speed',
            optionB: 'Lower on-state voltage drop at high currents',
            optionC: 'Simpler gate drive circuit',
            optionD: 'Better high-frequency performance',
            correctOption: 'B',
            explanation: 'IGBTs combine the high input impedance of MOSFETs with the low on-state voltage drop of BJTs. At high currents, IGBTs have significantly lower conduction losses than MOSFETs due to their lower on-state resistance. This makes them ideal for medium to high-power applications (above 1kW) such as motor drives and power supplies.',
            createdAt: new Date('2024-02-02').toISOString(),
        },

        // Topic 9: Control Systems (medium, hard, hard)
        {
            topicId: 9,
            difficulty: 'medium',
            questionText: 'What does a positive value of gain margin indicate in a control system?',
            optionA: 'The system is unstable',
            optionB: 'The system is stable',
            optionC: 'The system is critically damped',
            optionD: 'The system has zero steady-state error',
            correctOption: 'B',
            explanation: 'A positive gain margin indicates that the system is stable and can tolerate an increase in gain before becoming unstable. Gain margin is typically expressed in dB and represents the amount by which the gain can be increased before the system reaches instability. A gain margin of 6-12 dB is generally considered good design practice.',
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            topicId: 9,
            difficulty: 'hard',
            questionText: 'In a PID controller, what is the primary effect of the derivative term?',
            optionA: 'Eliminates steady-state error',
            optionB: 'Anticipates future error and improves transient response',
            optionC: 'Increases system stability unconditionally',
            optionD: 'Reduces overshoot by introducing lag',
            correctOption: 'B',
            explanation: 'The derivative term (D) responds to the rate of change of error, effectively anticipating future error trends. It provides a dampening effect that reduces overshoot and improves settling time. However, it also amplifies high-frequency noise, so it must be carefully tuned. The derivative action adds phase lead, improving transient response and stability margins.',
            createdAt: new Date('2024-02-04').toISOString(),
        },
        {
            topicId: 9,
            difficulty: 'hard',
            questionText: 'For a second-order system, what value of damping ratio (ζ) results in critically damped response?',
            optionA: 'ζ < 1',
            optionB: 'ζ = 0',
            optionC: 'ζ = 1',
            optionD: 'ζ > 1',
            correctOption: 'C',
            explanation: 'Critical damping occurs when ζ = 1, providing the fastest response without overshoot. When ζ < 1 (underdamped), the system oscillates; when ζ > 1 (overdamped), the response is slower. Critical damping represents the boundary between oscillatory and non-oscillatory behavior, making it ideal for applications requiring fast settling without overshoot.',
            createdAt: new Date('2024-02-05').toISOString(),
        },

        // Topic 10: Electrical Machines (easy, medium, medium)
        {
            topicId: 10,
            difficulty: 'easy',
            questionText: 'What is the main difference between a motor and a generator?',
            optionA: 'Motors use AC while generators use DC',
            optionB: 'Motors convert electrical energy to mechanical, generators do the opposite',
            optionC: 'Motors have commutators while generators have slip rings',
            optionD: 'There is no fundamental difference',
            correctOption: 'B',
            explanation: 'Motors convert electrical energy into mechanical energy (rotation), while generators convert mechanical energy into electrical energy. Both operate on the same electromagnetic principles (Faraday\'s law and Lorentz force), but in reverse. The same machine can often function as either a motor or generator depending on the direction of energy flow.',
            createdAt: new Date('2024-02-06').toISOString(),
        },
        {
            topicId: 10,
            difficulty: 'medium',
            questionText: 'Why is the starting current of an induction motor typically 5-7 times the rated current?',
            optionA: 'Due to high mechanical load at startup',
            optionB: 'Because back EMF is zero at standstill',
            optionC: 'Due to high magnetic saturation',
            optionD: 'Because of poor power factor at starting',
            correctOption: 'B',
            explanation: 'At standstill (starting), the rotor is stationary so there is no back EMF to oppose the applied voltage. The only limitation to current is the stator impedance, which is relatively low. As the motor accelerates, back EMF develops and limits the current. This high starting current necessitates the use of starting methods like star-delta or soft starters for large motors.',
            createdAt: new Date('2024-02-07').toISOString(),
        },
        {
            topicId: 10,
            difficulty: 'medium',
            questionText: 'What is the purpose of the damper winding in a synchronous machine?',
            optionA: 'To improve efficiency',
            optionB: 'To reduce voltage regulation',
            optionC: 'To provide starting torque and dampen oscillations',
            optionD: 'To increase power output',
            correctOption: 'C',
            explanation: 'Damper windings (amortisseur windings) serve two purposes: they provide starting torque for synchronous motors by operating like an induction motor during startup, and they dampen oscillations during load changes to maintain synchronism. The windings consist of copper bars embedded in the pole faces and short-circuited at both ends, acting as a squirrel cage winding.',
            createdAt: new Date('2024-02-08').toISOString(),
        },
    ];

    await db.insert(questions).values(sampleQuestions);
    
    console.log('✅ Questions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});