import { db } from '@/db';
import { userActivities } from '@/db/schema';

async function main() {
    const sampleActivities = [
        // user_001 activities (6000 points total - showing sample of 2300)
        // quiz_complete activities (20 total, 50 points each = 1000 points)
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"1","score":95,"topic":"Basic Circuits"}',
            createdAt: new Date('2024-11-25').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"2","score":88,"topic":"Ohms Law"}',
            createdAt: new Date('2024-11-23').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"3","score":92,"topic":"Series Circuits"}',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"4","score":85,"topic":"Parallel Circuits"}',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"5","score":90,"topic":"Power Calculations"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"6","score":94,"topic":"Kirchhoffs Laws"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"7","score":87,"topic":"Capacitors"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"8","score":91,"topic":"Inductors"}',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"9","score":89,"topic":"Transformers"}',
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"10","score":93,"topic":"Diodes"}',
            createdAt: new Date('2024-11-03').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"11","score":86,"topic":"Transistors"}',
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"12","score":90,"topic":"Op-Amps"}',
            createdAt: new Date('2024-10-29').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"13","score":88,"topic":"Digital Logic"}',
            createdAt: new Date('2024-10-27').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"14","score":92,"topic":"Microcontrollers"}',
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"15","score":84,"topic":"Arduino Basics"}',
            createdAt: new Date('2024-10-22').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"16","score":91,"topic":"Sensors"}',
            createdAt: new Date('2024-10-20').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"17","score":89,"topic":"Motors"}',
            createdAt: new Date('2024-10-18').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"18","score":87,"topic":"Power Supplies"}',
            createdAt: new Date('2024-10-15').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"19","score":93,"topic":"PCB Design"}',
            createdAt: new Date('2024-10-12').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"20","score":90,"topic":"Circuit Testing"}',
            createdAt: new Date('2024-10-10').toISOString(),
        },

        // calculator_use activities (15 total, 10 points each = 150 points)
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Ohms Law Calculator"}',
            createdAt: new Date('2024-11-24').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Series Resistor Calculator"}',
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Parallel Resistor Calculator"}',
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Power Calculator"}',
            createdAt: new Date('2024-11-17').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Voltage Divider Calculator"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"LED Resistor Calculator"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Capacitor Calculator"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Inductor Calculator"}',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Frequency Calculator"}',
            createdAt: new Date('2024-11-04').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Battery Life Calculator"}',
            createdAt: new Date('2024-10-30').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Wire Gauge Calculator"}',
            createdAt: new Date('2024-10-28').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Transformer Calculator"}',
            createdAt: new Date('2024-10-26').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"555 Timer Calculator"}',
            createdAt: new Date('2024-10-23').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Op-Amp Calculator"}',
            createdAt: new Date('2024-10-21').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Decibel Calculator"}',
            createdAt: new Date('2024-10-19').toISOString(),
        },

        // answer_accepted activities (10 total, 100 points each = 1000 points)
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"42","answer_id":"127"}',
            createdAt: new Date('2024-11-21').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"58","answer_id":"189"}',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"73","answer_id":"245"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"91","answer_id":"312"}',
            createdAt: new Date('2024-11-07').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"104","answer_id":"367"}',
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"125","answer_id":"423"}',
            createdAt: new Date('2024-10-31').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"137","answer_id":"478"}',
            createdAt: new Date('2024-10-24').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"149","answer_id":"534"}',
            createdAt: new Date('2024-10-17').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"162","answer_id":"589"}',
            createdAt: new Date('2024-10-14').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"178","answer_id":"645"}',
            createdAt: new Date('2024-10-11').toISOString(),
        },

        // daily_login activities (30 total, 5 points each = 150 points)
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-26"}',
            createdAt: new Date('2024-11-26').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-25"}',
            createdAt: new Date('2024-11-25').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-24"}',
            createdAt: new Date('2024-11-24').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-23"}',
            createdAt: new Date('2024-11-23').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-22"}',
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-21"}',
            createdAt: new Date('2024-11-21').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-20"}',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-19"}',
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-18"}',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-17"}',
            createdAt: new Date('2024-11-17').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-16"}',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-15"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-14"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-13"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-12"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-11"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-10"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-09"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-08"}',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-07"}',
            createdAt: new Date('2024-11-07').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-06"}',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-05"}',
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-04"}',
            createdAt: new Date('2024-11-04').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-03"}',
            createdAt: new Date('2024-11-03').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-02"}',
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-01"}',
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-10-31"}',
            createdAt: new Date('2024-10-31').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-10-30"}',
            createdAt: new Date('2024-10-30').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-10-29"}',
            createdAt: new Date('2024-10-29').toISOString(),
        },
        {
            userId: 'user_001',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-10-28"}',
            createdAt: new Date('2024-10-28').toISOString(),
        },

        // user_002 activities (1500 points total - showing 1275)
        // quiz_complete activities (12 total, 50 points each = 600 points)
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"1","score":82,"topic":"Basic Circuits"}',
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"2","score":78,"topic":"Ohms Law"}',
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"3","score":85,"topic":"Series Circuits"}',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"4","score":80,"topic":"Parallel Circuits"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"5","score":83,"topic":"Power Calculations"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"6","score":79,"topic":"Kirchhoffs Laws"}',
            createdAt: new Date('2024-11-07').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"7","score":81,"topic":"Capacitors"}',
            createdAt: new Date('2024-11-04').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"8","score":77,"topic":"Inductors"}',
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"9","score":84,"topic":"Transformers"}',
            createdAt: new Date('2024-10-28').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"10","score":76,"topic":"Diodes"}',
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"11","score":82,"topic":"Transistors"}',
            createdAt: new Date('2024-10-22').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"12","score":80,"topic":"Op-Amps"}',
            createdAt: new Date('2024-10-19').toISOString(),
        },

        // calculator_use activities (10 total, 10 points each = 100 points)
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Ohms Law Calculator"}',
            createdAt: new Date('2024-11-21').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Series Resistor Calculator"}',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Parallel Resistor Calculator"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Power Calculator"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Voltage Divider Calculator"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"LED Resistor Calculator"}',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Capacitor Calculator"}',
            createdAt: new Date('2024-11-03').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Frequency Calculator"}',
            createdAt: new Date('2024-10-30').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Battery Life Calculator"}',
            createdAt: new Date('2024-10-27').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Wire Gauge Calculator"}',
            createdAt: new Date('2024-10-24').toISOString(),
        },

        // answer_accepted activities (5 total, 100 points each = 500 points)
        {
            userId: 'user_002',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"35","answer_id":"98"}',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"52","answer_id":"156"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"68","answer_id":"214"}',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"84","answer_id":"278"}',
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"97","answer_id":"334"}',
            createdAt: new Date('2024-10-26').toISOString(),
        },

        // daily_login activities (15 total, 5 points each = 75 points)
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-23"}',
            createdAt: new Date('2024-11-23').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-22"}',
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-21"}',
            createdAt: new Date('2024-11-21').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-20"}',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-19"}',
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-18"}',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-17"}',
            createdAt: new Date('2024-11-17').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-16"}',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-15"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-14"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-13"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-12"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-11"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-10"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 'user_002',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-09"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },

        // user_003 activities (750 points total - showing 770)
        // quiz_complete activities (8 total, 50 points each = 400 points)
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"1","score":75,"topic":"Basic Circuits"}',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"2","score":72,"topic":"Ohms Law"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"3","score":78,"topic":"Series Circuits"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"4","score":74,"topic":"Parallel Circuits"}',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"5","score":76,"topic":"Power Calculations"}',
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"6","score":73,"topic":"Kirchhoffs Laws"}',
            createdAt: new Date('2024-10-29').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"7","score":77,"topic":"Capacitors"}',
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"8","score":71,"topic":"Inductors"}',
            createdAt: new Date('2024-10-21').toISOString(),
        },

        // calculator_use activities (12 total, 10 points each = 120 points)
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Ohms Law Calculator"}',
            createdAt: new Date('2024-11-17').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Series Resistor Calculator"}',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Parallel Resistor Calculator"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Power Calculator"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Voltage Divider Calculator"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"LED Resistor Calculator"}',
            createdAt: new Date('2024-11-07').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Capacitor Calculator"}',
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Inductor Calculator"}',
            createdAt: new Date('2024-11-03').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Frequency Calculator"}',
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Battery Life Calculator"}',
            createdAt: new Date('2024-10-30').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Wire Gauge Calculator"}',
            createdAt: new Date('2024-10-28').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Transformer Calculator"}',
            createdAt: new Date('2024-10-26').toISOString(),
        },

        // answer_accepted activities (2 total, 100 points each = 200 points)
        {
            userId: 'user_003',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"45","answer_id":"134"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"63","answer_id":"192"}',
            createdAt: new Date('2024-11-08').toISOString(),
        },

        // daily_login activities (10 total, 5 points each = 50 points)
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-19"}',
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-18"}',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-17"}',
            createdAt: new Date('2024-11-17').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-16"}',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-15"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-14"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-13"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-12"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-11"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_003',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-10"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },

        // user_004 activities (350 points total - showing 420)
        // quiz_complete activities (4 total, 50 points each = 200 points)
        {
            userId: 'user_004',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"1","score":68,"topic":"Basic Circuits"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"2","score":71,"topic":"Ohms Law"}',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"3","score":66,"topic":"Series Circuits"}',
            createdAt: new Date('2024-10-30').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"4","score":69,"topic":"Parallel Circuits"}',
            createdAt: new Date('2024-10-24').toISOString(),
        },

        // calculator_use activities (8 total, 10 points each = 80 points)
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Ohms Law Calculator"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Series Resistor Calculator"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Parallel Resistor Calculator"}',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Power Calculator"}',
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Voltage Divider Calculator"}',
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"LED Resistor Calculator"}',
            createdAt: new Date('2024-10-29').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Capacitor Calculator"}',
            createdAt: new Date('2024-10-26').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Battery Life Calculator"}',
            createdAt: new Date('2024-10-23').toISOString(),
        },

        // answer_accepted activities (1 total, 100 points each = 100 points)
        {
            userId: 'user_004',
            activityType: 'answer_accepted',
            pointsEarned: 100,
            metadata: '{"question_id":"51","answer_id":"167"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },

        // daily_login activities (8 total, 5 points each = 40 points)
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-16"}',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-15"}',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-14"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-13"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-12"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-11"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-10"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 'user_004',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-09"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },

        // user_005 activities (100 points total - showing 105)
        // quiz_complete activities (1 total, 50 points each = 50 points)
        {
            userId: 'user_005',
            activityType: 'quiz_complete',
            pointsEarned: 50,
            metadata: '{"quiz_id":"1","score":62,"topic":"Basic Circuits"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },

        // calculator_use activities (3 total, 10 points each = 30 points)
        {
            userId: 'user_005',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Ohms Law Calculator"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_005',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"Series Resistor Calculator"}',
            createdAt: new Date('2024-11-09').toISOString(),
        },
        {
            userId: 'user_005',
            activityType: 'calculator_use',
            pointsEarned: 10,
            metadata: '{"calculator_name":"LED Resistor Calculator"}',
            createdAt: new Date('2024-11-05').toISOString(),
        },

        // daily_login activities (5 total, 5 points each = 25 points)
        {
            userId: 'user_005',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-14"}',
            createdAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 'user_005',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-13"}',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 'user_005',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-12"}',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 'user_005',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-11"}',
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            userId: 'user_005',
            activityType: 'daily_login',
            pointsEarned: 5,
            metadata: '{"login_date":"2024-11-10"}',
            createdAt: new Date('2024-11-10').toISOString(),
        },
    ];

    await db.insert(userActivities).values(sampleActivities);
    
    console.log('✅ User activities seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});