import { db } from '@/db';
import { videoTutorials } from '@/db/schema';

async function main() {
    const sampleVideoTutorials = [
        {
            title: 'NEC Code Requirements for Residential Wiring',
            description: 'Comprehensive guide to National Electrical Code requirements for residential installations. Learn proper wire sizing, circuit protection, grounding requirements, and common code violations. Perfect for electricians preparing for licensing exams or homeowners planning electrical projects.',
            duration: '15:30',
            views: 2347,
            rating: 4.8,
            category: 'Code & Safety',
            level: 'Beginner',
            thumbnailUrl: '/thumbnails/nec-code.jpg',
            videoUrl: '/videos/nec-residential-wiring.mp4',
            author: 'Mike Johnson, PE',
            tags: 'NEC,residential,wiring,code,electrical,safety,licensing',
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-07-15').toISOString(),
        },
        {
            title: '3-Phase Motor Control Fundamentals',
            description: 'Master the basics of 3-phase motor control systems including contactors, overload relays, and control circuits. Understand motor starters, reversing circuits, and jogging operations. Includes hands-on wiring demonstrations and troubleshooting techniques for industrial applications.',
            duration: '22:45',
            views: 1842,
            rating: 4.7,
            category: 'Motor Controls',
            level: 'Intermediate',
            thumbnailUrl: '/thumbnails/3phase-motor.jpg',
            videoUrl: '/videos/3phase-motor-control.mp4',
            author: 'Sarah Martinez, Licensed Electrician',
            tags: '3-phase,motor control,contactors,industrial,starters,overload',
            createdAt: new Date('2024-08-22').toISOString(),
            updatedAt: new Date('2024-08-22').toISOString(),
        },
        {
            title: 'Power System Protection and Overcurrent Devices',
            description: 'Advanced training on power system protection schemes, overcurrent coordination, and protective device selection. Learn about circuit breakers, fuses, relays, and their coordination curves. Covers fault analysis, arc flash protection, and protective relay settings for commercial and industrial systems.',
            duration: '28:15',
            views: 892,
            rating: 4.9,
            category: 'Power Systems',
            level: 'Advanced',
            thumbnailUrl: '/thumbnails/power-protection.jpg',
            videoUrl: '/videos/power-system-protection.mp4',
            author: 'Dr. Robert Chen, PE',
            tags: 'protection,overcurrent,relays,circuit breakers,coordination,arc flash',
            createdAt: new Date('2024-09-10').toISOString(),
            updatedAt: new Date('2024-09-10').toISOString(),
        },
        {
            title: 'Grounding and Bonding Best Practices',
            description: 'Essential guide to proper grounding and bonding techniques for electrical systems. Learn the difference between grounding and bonding, equipment grounding conductors, ground fault protection, and NEC requirements. Includes practical installation techniques and common mistakes to avoid.',
            duration: '18:20',
            views: 1654,
            rating: 4.6,
            category: 'Code & Safety',
            level: 'Intermediate',
            thumbnailUrl: '/thumbnails/grounding-bonding.jpg',
            videoUrl: '/videos/grounding-bonding.mp4',
            author: 'Tom Williams, Master Electrician',
            tags: 'grounding,bonding,safety,NEC,equipment,ground fault,installation',
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-08-05').toISOString(),
        },
        {
            title: 'PLC Ladder Logic Programming Basics',
            description: 'Introduction to PLC programming using ladder logic. Learn fundamental concepts including inputs, outputs, contacts, coils, timers, and counters. Step-by-step programming examples for common automation tasks. Suitable for beginners with no prior PLC experience.',
            duration: '25:10',
            views: 2156,
            rating: 4.7,
            category: 'PLC & Automation',
            level: 'Beginner',
            thumbnailUrl: '/thumbnails/plc-basics.jpg',
            videoUrl: '/videos/plc-ladder-logic.mp4',
            author: 'Jennifer Lee, Automation Engineer',
            tags: 'PLC,ladder logic,programming,automation,timers,counters,industrial',
            createdAt: new Date('2024-07-28').toISOString(),
            updatedAt: new Date('2024-07-28').toISOString(),
        },
        {
            title: 'Residential Service Panel Installation',
            description: 'Complete guide to installing residential electrical service panels. Covers panel selection, main breaker sizing, circuit organization, and proper wire terminations. Learn load calculations, AFCI/GFCI requirements, and inspection-ready installation techniques following NEC standards.',
            duration: '19:45',
            views: 1923,
            rating: 4.8,
            category: 'Residential Wiring',
            level: 'Intermediate',
            thumbnailUrl: '/thumbnails/service-panel.jpg',
            videoUrl: '/videos/service-panel-install.mp4',
            author: 'Carlos Rodriguez, Licensed Contractor',
            tags: 'service panel,residential,installation,breakers,load calculations,NEC',
            createdAt: new Date('2024-09-18').toISOString(),
            updatedAt: new Date('2024-09-18').toISOString(),
        },
        {
            title: 'Transformer Sizing and Selection',
            description: 'Advanced guide to transformer sizing, selection, and application. Learn about kVA calculations, voltage regulation, efficiency considerations, and impedance matching. Covers distribution transformers, dry-type transformers, and special applications including harmonic mitigation.',
            duration: '24:30',
            views: 748,
            rating: 4.9,
            category: 'Power Systems',
            level: 'Advanced',
            thumbnailUrl: '/thumbnails/transformer-sizing.jpg',
            videoUrl: '/videos/transformer-selection.mp4',
            author: 'Dr. Patricia Anderson, PE',
            tags: 'transformers,sizing,selection,kVA,voltage regulation,power systems',
            createdAt: new Date('2024-10-02').toISOString(),
            updatedAt: new Date('2024-10-02').toISOString(),
        },
        {
            title: 'Solar PV System Design and Installation',
            description: 'Comprehensive course on solar photovoltaic system design and installation. Covers system sizing, panel selection, inverter configuration, battery storage integration, and grid interconnection. Includes NEC requirements for PV systems, grounding, and safety considerations.',
            duration: '31:20',
            views: 1567,
            rating: 4.7,
            category: 'Renewable Energy',
            level: 'Intermediate',
            thumbnailUrl: '/thumbnails/solar-pv.jpg',
            videoUrl: '/videos/solar-pv-design.mp4',
            author: 'Mark Thompson, Solar Installation Specialist',
            tags: 'solar,PV,photovoltaic,renewable energy,installation,design,inverters',
            createdAt: new Date('2024-08-14').toISOString(),
            updatedAt: new Date('2024-08-14').toISOString(),
        },
        {
            title: 'VFD (Variable Frequency Drive) Configuration',
            description: 'Advanced training on VFD configuration and programming for motor control applications. Learn parameter setup, acceleration/deceleration curves, PID control integration, and communication protocols. Covers troubleshooting techniques and energy efficiency optimization.',
            duration: '26:50',
            views: 634,
            rating: 4.8,
            category: 'Motor Controls',
            level: 'Advanced',
            thumbnailUrl: '/thumbnails/vfd-config.jpg',
            videoUrl: '/videos/vfd-configuration.mp4',
            author: 'David Kim, Senior Controls Engineer',
            tags: 'VFD,variable frequency drive,motor control,programming,PID,industrial',
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            title: 'Electrical Troubleshooting Techniques',
            description: 'Essential troubleshooting skills for electrical systems. Learn systematic approaches to diagnosing electrical problems using multimeters, clamp meters, and other test equipment. Covers common residential and commercial issues including circuit failures, voltage drops, and ground faults.',
            duration: '16:40',
            views: 2489,
            rating: 4.6,
            category: 'Electronics',
            level: 'Beginner',
            thumbnailUrl: '/thumbnails/troubleshooting.jpg',
            videoUrl: '/videos/electrical-troubleshooting.mp4',
            author: 'Lisa Brown, Electrical Instructor',
            tags: 'troubleshooting,diagnosis,multimeter,testing,circuits,voltage,ground fault',
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
    ];

    await db.insert(videoTutorials).values(sampleVideoTutorials);
    
    console.log('✅ Video tutorials seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});